use crate::analyze::{
    BuiltinNodeArgs, ComparisonOperator, FlowCallArgs, FlowChannelGetArgs, FlowChannelSetArgs,
    LoopMetric, LoopTimeUnit, PreparedProject,
};
use crate::model::{CompileError, SourceMap, SourceMapEntry};
use flow_ir::{ProjectVariableScope, ProjectVariableType, ValueType};
use serde_json::Value;
use std::collections::HashMap;

pub(crate) fn render_lua(
    project: &PreparedProject<'_>,
    entry_flow_id: &str,
    generation_id: &str,
) -> Result<(Vec<u8>, Vec<SourceMapEntry>), CompileError> {
    let mut writer = LuaWriter::default();
    let script_ui = project
        .manifest
        .runner_ui
        .as_ref()
        .filter(|ui| ui.version == Some(2));
    writer.line("-- @generated by flow-compiler; do not edit.");
    writer.line(&format!("-- generationId: {generation_id}"));
    for line in crate::popup_style_prefix(&project.manifest.debug_settings.popup_style)
        .map_err(|e| CompileError::Serialization(e.to_string()))?
        .lines()
    {
        writer.line(line);
    }
    writer.line("local __autoscript_debug_event = __autoscript_debug_event or function() end");
    writer.line("local __flows = {}");
    writer.line("local __recognition_ticks = {}");
    writer.line("local function __recognition_visit(key, every) local tick = __recognition_ticks[key] or 0; __recognition_ticks[key] = (tick + 1) % every; return tick == 0 end");
    writer
        .line("local function __checkpoint(flow, node, locals, globals, localTypes, globalTypes)");
    writer.line("  if not __autoscript_debug_capture then return end");
    writer.line("  __autoscript_debug_snapshot = {flowId=flow,nodeId=node,locals=locals,globals=globals,localTypes=localTypes,globalTypes=globalTypes}");
    writer.line("  if __autoscript_debug_target_node then");
    writer.line("    if flow ~= __autoscript_debug_target_flow or node ~= __autoscript_debug_target_node then return end");
    writer.line("    __autoscript_debug_target_node = nil; __autoscript_debug_target_flow = nil; __autoscript_debug_step = true");
    writer.line("    if __autoscript_debug_execute_target then __autoscript_debug_execute_target = nil; return end");
    writer.line("  end");
    writer.line(
        "  if __autoscript_debug_step then coroutine.yield('__AUTOSCRIPT_DEBUG_CHECKPOINT_V1') end",
    );
    writer.line("end");
    writer.line("local __globals = {}");
    writer.line("local __global_types = {}");
    for variable in &project.manifest.variables {
        if variable.scope == ProjectVariableScope::Global {
            writer.line(&format!(
                "__global_types[{}] = {}",
                lua_string(&variable.name)?,
                lua_string(variable_kind(variable.value_type))?
            ));
        }
    }
    writer.line("local function __default(kind) if kind == 'integer' or kind == 'number' then return 0 elseif kind == 'string' then return '' end end");
    writer.line("local function __variable_check(name, kind, value)");
    writer.line("  if value == nil or kind == nil then return end");
    writer.line("  local valid = (kind == 'string' and type(value) == 'string') or (kind == 'boolean' and type(value) == 'boolean')");
    writer.line("  if type(value) == 'number' and value == value and value ~= math.huge and value ~= -math.huge then valid = kind == 'number' or (kind == 'integer' and value % 1 == 0) or (kind == 'image' and value % 1 == 0 and value > 0) end");
    writer.line(
        "  if not valid then error('变量类型不匹配: ' .. name .. ' (' .. kind .. ')', 0) end",
    );
    writer.line("end");
    writer.line("local function __channel_value(value)");
    writer.line("  local kind = type(value)");
    writer.line("  if kind ~= 'boolean' and kind ~= 'string' and kind ~= 'number' then error('调用/返回参数必须为非空标量', 0) end");
    writer.line("  if kind == 'number' and (value ~= value or value == math.huge or value == -math.huge) then error('调用/返回参数必须为有限数值', 0) end");
    writer.line("  return value");
    writer.line("end");
    writer.line("local function __compare(left, operator, right)");
    writer.line("  if operator == \"equals\" then return left == right end");
    writer.line("  if operator == \"notEquals\" then return left ~= right end");
    writer.line("  local kind = type(left)");
    writer.line("  if kind ~= type(right) or (kind ~= \"number\" and kind ~= \"string\") then return false end");
    writer.line("  if operator == \"lessThan\" then return left < right end");
    writer.line("  if operator == \"lessOrEqual\" then return left <= right end");
    writer.line("  if operator == \"greaterThan\" then return left > right end");
    writer.line("  if operator == \"greaterOrEqual\" then return left >= right end");
    writer.line("  return false");
    writer.line("end");
    let mut entries = Vec::new();
    if project.flows.iter().any(|flow| {
        flow.document
            .nodes
            .iter()
            .any(|node| node.envelope.kind == "variable.calculate")
    }) {
        for line in crate::variable_expression::LUA_HELPERS.lines() {
            writer.line(line);
        }
    }
    for flow in &project.flows {
        writer.line("");
        writer.line(&format!(
            "__flows[{}] = function(__args)",
            lua_string(&flow.declaration.flow_id)?
        ));
        writer.line("  __args = __args or {}");
        writer.line("  local __locals, __local_types = {}, {}");
        for variable in &project.manifest.variables {
            if variable.scope == ProjectVariableScope::Flow
                && variable.flow_id.as_deref() == Some(&flow.declaration.flow_id)
            {
                writer.line(&format!(
                    "  __local_types[{}] = {}",
                    lua_string(&variable.name)?,
                    lua_string(variable_kind(variable.value_type))?
                ));
            }
        }
        for parameter in &flow.declaration.params {
            let kind = match parameter.value_type {
                ValueType::Boolean => "boolean",
                ValueType::Integer => "integer",
                ValueType::Number => "number",
                ValueType::String => "string",
            };
            writer.line(&format!(
                "  __local_types[{}] = {}",
                lua_string(&parameter.name)?,
                lua_string(kind)?
            ));
        }
        writer.line(
            "  for name, kind in pairs(__local_types) do __locals[name] = __default(kind) end",
        );
        if script_ui.is_some() {
            writer.line(&format!(
                "  local __ui_bound = (__ui_initial_locals or {{}})[{}] or {{}}",
                lua_string(&flow.declaration.flow_id)?
            ));
        }
        writer.line("  local __vars = setmetatable({}, {");
        writer.line("    __index = function(_, name) if __local_types[name] or not __global_types[name] then return __locals[name] end return __globals[name] end,");
        writer.line("    __newindex = function(_, name, value) local kind = __local_types[name] or __global_types[name]; __variable_check(name, kind, value); if __local_types[name] or not __global_types[name] then __locals[name] = value else __globals[name] = value end end");
        writer.line("  })");
        if script_ui.is_some() {
            writer.line("  local __meta = getmetatable(__vars); local __read, __write = __meta.__index, __meta.__newindex");
            writer.line("  __meta.__index = function(t,name) if __ui_bound[name] ~= nil then return __ui_bound[name] end return __read(t,name) end");
            writer.line("  __meta.__newindex = function(t,name,value) __write(t,name,value); if __ui_bound[name] ~= nil then __ui_bound[name]=value end end");
        }
        if script_ui.is_some() {
            writer.line(&format!("  for name, value in pairs((__ui_initial_locals or {{}})[{}] or {{}}) do __vars[name] = value end", lua_string(&flow.declaration.flow_id)?));
        }
        writer.line("  local __call_args = {}");
        writer.line("  local __last_return_values = {}");
        writer.line("  local __return_values = {}");
        writer.line("  local function __checked_return()");
        if let Some(declaration) = &flow.declaration.returns {
            if !declaration.nullable {
                writer.line(
                    "    if __return_values[1] == nil then error(\"插件返回值不能为空\", 0) end",
                );
            }
            let invalid = match declaration.value_type {
                ValueType::Boolean => "type(__return_values[1]) ~= \"boolean\"",
                ValueType::Integer => {
                    "type(__return_values[1]) ~= \"number\" or __return_values[1] % 1 ~= 0"
                }
                ValueType::Number => "type(__return_values[1]) ~= \"number\"",
                ValueType::String => "type(__return_values[1]) ~= \"string\"",
            };
            writer.line(&format!(
                "    if __return_values[1] ~= nil and ({invalid}) then error(\"插件返回类型不匹配\", 0) end"
            ));
        }
        writer.line("    return __return_values");
        writer.line("  end");
        writer.indented(
            1,
            &format!(
                "__autoscript_debug_event(\"flowStart\", {}, \"\", \"\")",
                lua_string(&flow.declaration.flow_id)?
            ),
        );
        for parameter in &flow.declaration.params {
            let access = format!("__args[{}]", lua_string(&parameter.name)?);
            let invalid = match parameter.value_type {
                ValueType::Boolean => format!("type({access}) ~= \"boolean\""),
                ValueType::Integer => format!("type({access}) ~= \"number\" or {access} % 1 ~= 0"),
                ValueType::Number => format!("type({access}) ~= \"number\""),
                ValueType::String => format!("type({access}) ~= \"string\""),
            };
            writer.line(&format!(
                "  if {} then error({}, 0) end",
                if parameter.required {
                    format!("{access} == nil or ({invalid})")
                } else {
                    format!("{access} ~= nil and ({invalid})")
                },
                lua_string(&format!("插件参数 {} 类型不匹配", parameter.name))?,
            ));
            writer.line(&format!(
                "  __vars[{}] = __args[{}]",
                lua_string(&parameter.name)?,
                lua_string(&parameter.name)?
            ));
        }
        let canonical_nodes = flow
            .document
            .canonical_nodes()
            .ok_or_else(|| CompileError::Serialization("missing canonical node order".into()))?
            .collect::<Vec<_>>();
        let mut blocks: HashMap<&str, Vec<&flow_ir::FlowNode>> = HashMap::new();
        let disabled = flow.document.disabled_node_ids();
        for node in canonical_nodes {
            if disabled.contains(node.envelope.node_id.as_str()) {
                continue;
            }
            blocks
                .entry(node.envelope.block_id.as_str())
                .or_default()
                .push(node);
        }
        render_flow_body(
            project,
            &flow.declaration.flow_id,
            &flow.document.root_block_id,
            &blocks,
            &mut writer,
            &mut entries,
        )?;
        writer.indented(
            1,
            &format!(
                "__autoscript_debug_event(\"flowReturn\", {}, \"\", \"\")",
                lua_string(&flow.declaration.flow_id)?
            ),
        );
        writer.line("  return __checked_return()");
        writer.line("end");
    }
    let mut event_branches = Vec::new();
    if let Some(ui) = script_ui {
        for field in &ui.fields {
            let style = field
                .ui
                .as_ref()
                .ok_or_else(|| CompileError::Serialization("missing UI layout".into()))?;
            if let Some(events) = style.get("events").and_then(Value::as_object) {
                for (event, action) in events {
                    if let Some(target) = action.as_str().and_then(|a| a.strip_prefix("flow:")) {
                        let converted = match field.kind {
                            flow_ir::RunnerUiFieldKind::Integer => {
                                "assert(tonumber(__value), '界面数值无效')".to_owned()
                            }
                            flow_ir::RunnerUiFieldKind::Boolean => "(__value == 'true')".to_owned(),
                            _ => "__value".to_owned(),
                        };
                        event_branches.push(format!("    if __event == {} then __flows[{}]({{controlId={},event={},value={converted}}}) end",
                            lua_string(&format!("{}:{event}",field.id))?, lua_string(target)?, lua_string(&field.id)?, lua_string(event)?));
                    }
                }
            }
        }
    }
    let dispatch_ui = !event_branches.is_empty()
        || script_ui.is_some_and(|ui| {
            ui.fields.iter().any(|f| {
                f.ui.as_ref()
                    .and_then(|p| p.get("binding"))
                    .and_then(Value::as_str)
                    .is_some_and(|b| !b.starts_with("param:"))
            })
        });
    if dispatch_ui {
        writer.line("local function __run_ui_events()");
        writer.line("  while true do");
        writer.line("    local __event = UI.waitEvent()");
        writer.line("    local __id = __event:match('^([^:]+):')");
        writer.line("    local __value = UI.getValue(__id)");
        if let Some(ui) = script_ui {
            for field in &ui.fields {
                if let Some(binding) = field
                    .ui
                    .as_ref()
                    .and_then(|p| p.get("binding"))
                    .and_then(Value::as_str)
                {
                    let parts = binding.split(':').collect::<Vec<_>>();
                    if parts[0] == "param" {
                        continue;
                    }
                    let target = if parts[0] == "global" {
                        "__globals".to_owned()
                    } else {
                        format!("__ui_initial_locals[{}]", lua_string(parts[1])?)
                    };
                    let converted = match field.kind {
                        flow_ir::RunnerUiFieldKind::Integer => {
                            "assert(tonumber(__value),'界面数值无效')"
                        }
                        flow_ir::RunnerUiFieldKind::Boolean => "(__value == 'true' and 1 or 0)",
                        _ => "__value",
                    };
                    writer.line(&format!(
                        "    if __id == {} then {target}[{}] = {converted} end",
                        lua_string(&field.id)?,
                        lua_string(parts.last().unwrap_or(&""))?
                    ));
                }
            }
        }
        for line in &event_branches {
            writer.line(line);
        }
        writer.line("  end");
        writer.line("end");
    }
    writer.line("");
    writer.line("return function(__entry_args)");
    writer.line("  __recognition_ticks = {}");
    writer.line("  __globals = {}");
    writer
        .line("  for name, kind in pairs(__global_types) do __globals[name] = __default(kind) end");
    if script_ui.is_some() {
        writer.line("  __entry_args = __entry_args or __ui_entry_args");
        writer.line("  for name, value in pairs(__ui_initial_globals or {}) do __variable_check(name,__global_types[name],value); __globals[name]=value end");
    }
    if !dispatch_ui {
        writer.line(&format!(
            "  __flows[{}](__entry_args or {{}})",
            lua_string(entry_flow_id)?
        ));
    } else {
        writer.line(&format!(
            "  if __ui_debug_skip_events then __flows[{}](__entry_args or {{}}); return nil end",
            lua_string(entry_flow_id)?
        ));
        writer.line(&format!(
            "  Task.spawn(function() __flows[{}](__entry_args or {{}}) end)",
            lua_string(entry_flow_id)?
        ));
        writer.line("  __run_ui_events()");
    }
    writer.line("  return nil");
    writer.line("end");
    Ok((writer.output.into_bytes(), entries))
}

fn variable_kind(kind: ProjectVariableType) -> &'static str {
    match kind {
        ProjectVariableType::Integer => "integer",
        ProjectVariableType::Number => "number",
        ProjectVariableType::String => "string",
        ProjectVariableType::Image => "image",
    }
}

enum RenderEvent<'a> {
    Block(&'a str, usize),
    Node(&'a flow_ir::FlowNode, usize),
    Line(usize, &'static str),
    OwnedLine(usize, String),
}

fn render_flow_body<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    root_block_id: &'a str,
    blocks: &HashMap<&'a str, Vec<&'a flow_ir::FlowNode>>,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
) -> Result<(), CompileError> {
    let mut events = vec![RenderEvent::Block(root_block_id, 1)];
    while let Some(event) = events.pop() {
        match event {
            RenderEvent::Line(indent, line) => writer.indented(indent, line),
            RenderEvent::OwnedLine(indent, line) => writer.indented(indent, &line),
            RenderEvent::Block(block_id, indent) => {
                for node in blocks.get(block_id).into_iter().flatten().rev() {
                    events.push(RenderEvent::Node(node, indent));
                }
            }
            RenderEvent::Node(node, indent) => {
                writer.indented(
                    indent,
                    &format!(
                        "__checkpoint({}, {}, __locals, __globals, __local_types, __global_types)",
                        lua_string(flow_id)?,
                        lua_string(&node.envelope.node_id)?,
                    ),
                );
                render_node(project, flow_id, node, indent, writer, entries, &mut events)?;
            }
        }
    }
    Ok(())
}

fn render_node<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    node: &'a flow_ir::FlowNode,
    indent: usize,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
    events: &mut Vec<RenderEvent<'a>>,
) -> Result<(), CompileError> {
    let kind = node.envelope.kind.as_str();
    match kind {
        "task.noop" => {
            writer.indented(indent, "do end");
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "task.comment" => {
            let message = node
                .envelope
                .args
                .get("message")
                .and_then(Value::as_str)
                .ok_or_else(|| {
                    CompileError::Serialization("validated comment is missing".into())
                })?;
            writer.indented(
                indent,
                &format!("-- {}", message.replace(['\r', '\n'], " ")),
            );
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "flow.call" | "task.spawn" | "timer.every" => {
            let call = project.calls.get(&node.envelope.node_id).ok_or_else(|| {
                CompileError::Serialization("validated flow.call is missing".into())
            })?;
            let rendered = render_call(project, call)?;
            let kind = node.envelope.kind.as_str();
            if kind == "flow.call" {
                writer.indented(indent, &format!("__last_return_values = {rendered}"));
            } else {
                // Freeze scalar arguments at registration, not at a future timer tick.
                let function = format!("__flows[{}]", lua_string(&call.target_flow_id)?);
                let payload = render_call_payload(project, call)?;
                let api = if kind == "timer.every" {
                    format!("Timer.every({},", call.period_ms.unwrap_or(10))
                } else {
                    "Task.spawn(".to_owned()
                };
                writer.indented(indent,&format!("do local __payload={payload}; __vars[{}]={api}function() {function}(__payload) end) end",lua_string(call.result_variable.as_deref().unwrap_or("jobId"))?));
            }
            writer.indented(indent, "__call_args = {}");
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "control.loopmetric" | "control.loopcheck" => {
            let owner = nearest_loop(project, flow_id, node).ok_or_else(invalid_builtin_variant)?;
            let count = if owner.envelope.kind == "control.repeat" {
                "__loop_count"
            } else {
                "__iterations"
            };
            let line = match builtin_arguments(project, node)? {
                BuiltinNodeArgs::LoopMetric(args) => {
                    let value = match args.metric {
                        LoopMetric::Count => count.to_owned(),
                        LoopMetric::Elapsed => {
                            let elapsed = "(System.elapsedRealtimeMillis() - __loop_started_at)";
                            if args.unit == LoopTimeUnit::Milliseconds {
                                elapsed.to_owned()
                            } else {
                                format!("{elapsed} / {}", args.unit.factor())
                            }
                        }
                    };
                    format!("__vars[{}] = {value}", lua_string(&args.name)?)
                }
                BuiltinNodeArgs::LoopCheck(args) => {
                    let limit = if let Some(name) = &args.limit_variable {
                        format!("__vars[{}]", lua_string(name)?)
                    } else {
                        args.limit.to_string()
                    };
                    let (value, max) = if args.metric == LoopMetric::Count {
                        (count, 1_000_000)
                    } else {
                        (
                            "(System.elapsedRealtimeMillis() - __loop_started_at)",
                            86_400_000,
                        )
                    };
                    format!("do local __limit={limit}; if type(__limit) ~= 'number' or __limit ~= __limit or __limit == math.huge or __limit == -math.huge then error('循环检查阈值无效',0) end; __limit=__limit*{}; if __limit < 1 or __limit > {max} or __limit % 1 ~= 0 then error('循环检查阈值越界或精度不足',0) end; if {value} >= __limit then break end end", args.unit.factor())
                }
                _ => return Err(invalid_builtin_variant()),
            };
            let start = writer.next_line();
            writer.indented(indent, &line);
            push_source_entry(flow_id, node, start, writer.current_line(), entries);
        }
        "control.break" | "flow.return" | "control.label" | "control.goto" => {
            let line = match kind {
                "control.break" => "do break end".to_owned(),
                "flow.return" => "do return __checked_return() end".to_owned(),
                "control.label" | "control.goto" => {
                    let name = node
                        .envelope
                        .args
                        .get("name")
                        .and_then(Value::as_str)
                        .ok_or_else(|| {
                            CompileError::Serialization("validated jump name is missing".into())
                        })?;
                    if kind == "control.label" {
                        format!("::__jump_{name}::")
                    } else {
                        format!("goto __jump_{name}")
                    }
                }
                _ => unreachable!(),
            };
            writer.indented(indent, &line);
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "flow.argument.set" | "flow.return.set" => {
            let args: FlowChannelSetArgs = serde_json::from_value(node.envelope.args.clone())
                .map_err(|error| CompileError::Serialization(error.to_string()))?;
            let value = if let Some(name) = args.value_variable.as_deref() {
                format!("__vars[{}]", lua_string(name)?)
            } else {
                lua_literal(args.value.as_ref().ok_or_else(|| {
                    CompileError::Serialization("validated channel value is missing".into())
                })?)?
            };
            let destination = if kind == "flow.argument.set" {
                format!("__call_args[{}]", args.index)
            } else {
                format!("__return_values[{}]", args.index)
            };
            writer.indented(indent, &format!("{destination} = __channel_value({value})"));
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "flow.argument.get" | "flow.return.get" => {
            let args: FlowChannelGetArgs = serde_json::from_value(node.envelope.args.clone())
                .map_err(|error| CompileError::Serialization(error.to_string()))?;
            let source = if kind == "flow.argument.get" {
                format!("__args[{}]", args.index)
            } else {
                format!("(__last_return_values or {{}})[{}]", args.index)
            };
            writer.indented(
                indent,
                &format!("__vars[{}] = {source}", lua_string(&args.target_variable)?),
            );
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "task.sleep"
        | "ui.get"
        | "ui.set"
        | "ui.command"
        | "task.cancel"
        | "timer.cancel"
        | "task.log"
        | "task.prompt"
        | "task.runprompt"
        | "input.tap"
        | "input.pointerdown"
        | "input.pointermove"
        | "input.pointerup"
        | "input.swipe"
        | "input.keyevent"
        | "variable.set"
        | "variable.calculate"
        | "variable.copy"
        | "screen.capture"
        | "screen.release"
        | "vision.getcolor"
        | "vision.findcolor"
        | "vision.comparecolor"
        | "vision.findmulticolor"
        | "vision.countcolor"
        | "vision.findallcolor"
        | "vision.findimage"
        | "vision.findgray"
        | "ocr.alphanumeric"
        | "ocr.glyph"
        | "legacy.duodianzhaose"
        | "legacy.duodianbise"
        | "legacy.getrectcolornum"
        | "legacy.getrgbcolor" => {
            let arguments = builtin_arguments(project, node)?;
            let key = format!("{flow_id}:{}", node.envelope.node_id);
            let rendered = if let BuiltinNodeArgs::FindImage(value) = arguments {
                let numeric_found = project
                    .flows
                    .iter()
                    .find(|flow| flow.declaration.flow_id == flow_id)
                    .and_then(|flow| {
                        flow.declaration
                            .params
                            .iter()
                            .find(|parameter| parameter.name == value.found_variable)
                    })
                    .map_or_else(
                        || {
                            matches!(
                                crate::analyze::declared_variable_type(
                                    project.manifest,
                                    flow_id,
                                    &value.found_variable
                                ),
                                Some(ProjectVariableType::Integer | ProjectVariableType::Number)
                            )
                        },
                        |parameter| {
                            matches!(parameter.value_type, ValueType::Integer | ValueType::Number)
                        },
                    );
                render_find_image(value, &key, numeric_found)?
            } else {
                render_builtin(arguments, &key)?
            };
            writer.indented(indent, &rendered);
            match arguments {
                BuiltinNodeArgs::VariableCalculate(value) => writer.indented(
                    indent,
                    &format!(
                        "__autoscript_debug_event(\"variable\", {}, {}, __vars[{}])",
                        lua_string(flow_id)?,
                        lua_string(&value.name)?,
                        lua_string(&value.name)?
                    ),
                ),
                BuiltinNodeArgs::VariableSet(value) => writer.indented(
                    indent,
                    &format!(
                        "__autoscript_debug_event(\"variable\", {}, {}, __vars[{}])",
                        lua_string(flow_id)?,
                        lua_string(&value.name)?,
                        lua_string(&value.name)?,
                    ),
                ),
                BuiltinNodeArgs::VariableCopy(value) => writer.indented(
                    indent,
                    &format!(
                        "__autoscript_debug_event(\"variable\", {}, {}, __vars[{}])",
                        lua_string(flow_id)?,
                        lua_string(&value.name)?,
                        lua_string(&value.name)?,
                    ),
                ),
                BuiltinNodeArgs::FindImage(value) => writer.indented(
                    indent,
                    &format!(
                        "__autoscript_debug_event(\"imageSearch\", {}, {}, __vars[{}])",
                        lua_string(flow_id)?,
                        lua_string(&value.image_path)?,
                        lua_string(&value.found_variable)?,
                    ),
                ),
                _ => {}
            }
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "control.if" => render_if(project, flow_id, node, indent, writer, entries, events)?,
        "control.repeat" => {
            render_repeat(project, flow_id, node, indent, writer, entries, events)?;
        }
        "control.while" => {
            render_while(project, flow_id, node, indent, writer, entries, events)?;
        }
        _ => {
            return Err(CompileError::UnsupportedNodeKind {
                node_id: node.envelope.node_id.clone(),
                kind: kind.to_owned(),
            });
        }
    }
    Ok(())
}

fn render_if<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    node: &'a flow_ir::FlowNode,
    indent: usize,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
    events: &mut Vec<RenderEvent<'a>>,
) -> Result<(), CompileError> {
    let BuiltinNodeArgs::If(arguments) = builtin_arguments(project, node)? else {
        return Err(invalid_builtin_variant());
    };
    writer.indented(
        indent,
        &format!(
            "__autoscript_debug_event(\"jump\", {}, \"如果\", {})",
            lua_string(flow_id)?,
            render_comparison(arguments)?,
        ),
    );
    writer.indented(
        indent,
        &format!("if {} then", render_comparison(arguments)?),
    );
    push_source_entry(
        flow_id,
        node,
        writer.current_line(),
        writer.current_line(),
        entries,
    );
    events.push(RenderEvent::Line(indent, "end"));
    events.push(RenderEvent::Block(child_block(node, "else")?, indent + 1));
    events.push(RenderEvent::Line(indent, "else"));
    for (index, branch) in arguments.else_if.iter().enumerate().rev() {
        events.push(RenderEvent::Block(
            child_block(node, &format!("elseIf{index}"))?,
            indent + 1,
        ));
        events.push(RenderEvent::OwnedLine(
            indent,
            format!(
                "elseif {} then",
                comparison_expression(
                    &branch.variable,
                    branch.operator,
                    &branch.value,
                    branch.value_variable.as_deref(),
                )?
            ),
        ));
    }
    events.push(RenderEvent::Block(child_block(node, "then")?, indent + 1));
    Ok(())
}

fn render_repeat<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    node: &'a flow_ir::FlowNode,
    indent: usize,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
    events: &mut Vec<RenderEvent<'a>>,
) -> Result<(), CompileError> {
    let BuiltinNodeArgs::Repeat(arguments) = builtin_arguments(project, node)? else {
        return Err(invalid_builtin_variant());
    };
    writer.indented(indent, "do");
    writer.indented(
        indent + 1,
        "local __loop_started_at = System.elapsedRealtimeMillis()",
    );
    writer.indented(indent + 1, "local __loop_count = 0");
    if let Some(name) = &arguments.times_variable {
        writer.indented(
            indent + 1,
            &format!("local __loop_times = __vars[{}]", lua_string(name)?),
        );
        writer.indented(indent + 1, "if type(__loop_times) ~= \"number\" or __loop_times % 1 ~= 0 or __loop_times < 0 or __loop_times > 1000000 then error(\"control.repeat timesVariable is invalid\", 0) end");
    } else {
        writer.indented(
            indent + 1,
            &format!("local __loop_times = {}", arguments.times),
        );
    }
    let start = writer.next_line();
    writer.indented(indent + 1, "for __index = 1, __loop_times do");
    writer.indented(indent + 2, "__loop_count = __index");
    writer.indented(
        indent + 2,
        &format!(
            "__autoscript_debug_event(\"loop\", {}, \"次数循环\", __loop_count)",
            lua_string(flow_id)?,
        ),
    );
    if let Some(name) = &arguments.index_variable {
        writer.indented(
            indent + 2,
            &format!("__vars[{}] = __index", lua_string(name)?),
        );
    }
    if let Some(name) = &arguments.elapsed_variable {
        writer.indented(
            indent + 2,
            &format!(
                "__vars[{}] = System.elapsedRealtimeMillis() - __loop_started_at",
                lua_string(name)?
            ),
        );
    }
    push_source_entry(flow_id, node, start, writer.current_line(), entries);
    events.push(RenderEvent::Line(indent, "end"));
    events.push(RenderEvent::Line(indent + 1, "end"));
    events.push(RenderEvent::Block(child_block(node, "body")?, indent + 2));
    Ok(())
}

fn render_while<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    node: &'a flow_ir::FlowNode,
    indent: usize,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
    events: &mut Vec<RenderEvent<'a>>,
) -> Result<(), CompileError> {
    let BuiltinNodeArgs::While(arguments) = builtin_arguments(project, node)? else {
        return Err(invalid_builtin_variant());
    };
    writer.indented(indent, "do");
    writer.indented(indent + 1, "local __iterations = 0");
    writer.indented(
        indent + 1,
        "local __loop_started_at = System.elapsedRealtimeMillis()",
    );
    if let Some(name) = &arguments.duration_variable {
        writer.indented(
            indent + 1,
            &format!("local __loop_duration = __vars[{}]", lua_string(name)?),
        );
        writer.indented(indent + 1, "if type(__loop_duration) ~= \"number\" or __loop_duration ~= __loop_duration or __loop_duration == math.huge or __loop_duration == -math.huge then error(\"control.while durationVariable is invalid\", 0) end");
        writer.indented(
            indent + 1,
            &format!(
                "__loop_duration = __loop_duration * {}",
                arguments.duration_unit.factor()
            ),
        );
        writer.indented(indent + 1, "if __loop_duration < 1 or __loop_duration > 86400000 or __loop_duration % 1 ~= 0 then error(\"control.while durationVariable is out of range\", 0) end");
    } else if let Some(duration) = arguments.duration_ms {
        writer.indented(indent + 1, &format!("local __loop_duration = {duration}"));
    }
    let start = writer.next_line();
    writer.indented(
        indent + 1,
        &format!(
            "while {}{} do",
            if arguments.always {
                "true".to_owned()
            } else {
                render_while_comparison(arguments)?
            },
            if arguments.duration_ms.is_some() || arguments.duration_variable.is_some() {
                " and System.elapsedRealtimeMillis() - __loop_started_at < __loop_duration"
            } else {
                ""
            }
        ),
    );
    writer.indented(indent + 2, "__iterations = __iterations + 1");
    writer.indented(
        indent + 2,
        &format!(
            "__autoscript_debug_event(\"loop\", {}, \"条件循环\", __iterations)",
            lua_string(flow_id)?,
        ),
    );
    if let Some(name) = &arguments.iteration_variable {
        writer.indented(
            indent + 2,
            &format!("__vars[{}] = __iterations", lua_string(name)?),
        );
    }
    if let Some(name) = &arguments.elapsed_variable {
        writer.indented(
            indent + 2,
            &format!(
                "__vars[{}] = System.elapsedRealtimeMillis() - __loop_started_at",
                lua_string(name)?
            ),
        );
    }
    writer.indented(
        indent + 2,
        &format!(
            "if __iterations > {} then error(\"control.while iteration limit exceeded\", 0) end",
            arguments.max_iterations
        ),
    );
    push_source_entry(flow_id, node, start, writer.current_line(), entries);
    events.push(RenderEvent::Line(indent, "end"));
    events.push(RenderEvent::Line(indent + 1, "end"));
    events.push(RenderEvent::Block(child_block(node, "body")?, indent + 2));
    Ok(())
}

fn builtin_arguments<'a>(
    project: &'a PreparedProject<'_>,
    node: &flow_ir::FlowNode,
) -> Result<&'a BuiltinNodeArgs, CompileError> {
    project
        .builtins
        .get(&node.envelope.node_id)
        .ok_or_else(|| CompileError::Serialization("validated builtin node is missing".into()))
}

fn nearest_loop<'a>(
    project: &'a PreparedProject<'_>,
    flow_id: &str,
    node: &flow_ir::FlowNode,
) -> Option<&'a flow_ir::FlowNode> {
    let flow = project
        .flows
        .iter()
        .find(|flow| flow.declaration.flow_id == flow_id)?;
    let mut parent = node.envelope.parent_id.as_deref();
    while let Some(id) = parent {
        let owner = flow
            .document
            .nodes
            .iter()
            .find(|node| node.envelope.node_id == id)?;
        if matches!(
            owner.envelope.kind.as_str(),
            "control.repeat" | "control.while"
        ) {
            return Some(owner);
        }
        parent = owner.envelope.parent_id.as_deref();
    }
    None
}

fn child_block<'a>(node: &'a flow_ir::FlowNode, name: &str) -> Result<&'a str, CompileError> {
    node.envelope
        .child_blocks
        .get(name)
        .map(String::as_str)
        .ok_or_else(|| CompileError::Serialization("validated child block is missing".into()))
}

fn push_source_entry(
    flow_id: &str,
    node: &flow_ir::FlowNode,
    start: u32,
    end: u32,
    entries: &mut Vec<SourceMapEntry>,
) {
    entries.push(SourceMapEntry {
        flow_id: flow_id.to_owned(),
        node_id: node.envelope.node_id.clone(),
        lua_start_line: start,
        lua_end_line: end,
    });
}

fn render_builtin(arguments: &BuiltinNodeArgs, key: &str) -> Result<String, CompileError> {
    if let BuiltinNodeArgs::Ui(args, kind) = arguments {
        let id = lua_string(&args.control_id)?;
        let value = args
            .value_variable
            .as_ref()
            .map(|v| lua_string(v).map(|name| format!("tostring(__vars[{name}])")))
            .transpose()?
            .unwrap_or(lua_string(&args.value)?);
        return Ok(match kind.as_str() {
            "ui.get" => format!(
                "__vars[{}] = UI.getValue({id})",
                lua_string(args.result_variable.as_deref().unwrap_or(""))?
            ),
            "ui.set" => format!("UI.setValue({id},{value})"),
            _ => format!("UI.command({id},{},{value})", lua_string(&args.operation)?),
        });
    }
    match arguments {
        BuiltinNodeArgs::Ui(_,_) => unreachable!(),
        BuiltinNodeArgs::Sleep(value) => {
            if let Some(name) = &value.milliseconds_variable {
                Ok(format!(
                "do local __delay = __vars[{}]; if type(__delay) ~= \"number\" or __delay % 1 ~= 0 or __delay < 0 or __delay > 86400000 then error(\"等待时间变量无效\", 0) end; Task.sleep(__delay) end",
                lua_string(name)?
            ))
            } else {
                Ok(format!("Task.sleep({})", value.milliseconds))
            }
        }
        BuiltinNodeArgs::JobCancel(value, timer) => Ok(format!(
            "{}.cancel(__vars[{}])",
            if *timer { "Timer" } else { "Task" },
            lua_string(&value.id_variable)?
        )),
        BuiltinNodeArgs::Log(value) => {
            let level = match value.level {
                crate::analyze::LogLevel::Info => "info",
                crate::analyze::LogLevel::Warn => "warn",
                crate::analyze::LogLevel::Error => "error",
            };
            let message = match value.value_variable.as_deref() {
                Some(name) => format!("tostring(__vars[{}])", lua_string(name)?),
                None => lua_string(&value.message)?,
            };
            Ok(format!("Log.{level}({message})"))
        }
        BuiltinNodeArgs::Prompt(value) => {
            let message = match value.value_variable.as_deref() {
                Some(name) => format!("tostring(__vars[{}])", lua_string(name)?),
                None => lua_string(&value.message)?,
            };
            Ok(format!("Prompt.toast({message})"))
        }
        BuiltinNodeArgs::RunPrompt(value) => {
            let message = match value.value_variable.as_deref() {
                Some(name) => format!("tostring(__vars[{}])", lua_string(name)?),
                None => lua_string(&value.message)?,
            };
            Ok(format!("Prompt.show({message})"))
        }
        BuiltinNodeArgs::Tap(value) => Ok(format!("Input.tap({},{})", value.x, value.y)),
        BuiltinNodeArgs::PointerDown(value) => {
            Ok(format!("Input.pointerDown({},{})", value.x, value.y))
        }
        BuiltinNodeArgs::PointerMove(value) => {
            Ok(format!("Input.pointerMove({},{})", value.x, value.y))
        }
        BuiltinNodeArgs::PointerUp => Ok("Input.pointerUp()".into()),
        BuiltinNodeArgs::Swipe(value) => Ok(format!(
            "Input.swipe({},{},{},{},{})",
            value.x1, value.y1, value.x2, value.y2, value.duration_ms
        )),
        BuiltinNodeArgs::KeyEvent(value) => Ok(format!("Input.keyEvent({})", value.key_code)),
        BuiltinNodeArgs::VariableSet(value) => Ok(format!(
            "__vars[{}] = {}",
            lua_string(&value.name)?,
            lua_literal(&value.value)?
        )),
        BuiltinNodeArgs::VariableCalculate(value) => Ok(format!(
            "__vars[{name}] = __calc_source({expression},__local_types[{name}] or __global_types[{name}])",
            name = lua_string(&value.name)?,
            expression = crate::variable_expression::render(&value.expression)
                .map_err(|error| CompileError::Serialization(error.to_owned()))?
        )),
        BuiltinNodeArgs::VariableCopy(value) => Ok(format!(
            "__vars[{}] = __vars[{}]",
            lua_string(&value.name)?,
            lua_string(&value.source_name)?
        )),
        BuiltinNodeArgs::ScreenCapture(value) => Ok(format!(
            "__vars[{}] = Screen.cache(Screen.capture())",
            lua_string(&value.result_variable)?
        )),
        BuiltinNodeArgs::ScreenRelease(value) => Ok(format!(
            "Screen.release(__vars[{}]); __vars[{}] = nil",
            lua_string(&value.frame_variable)?,
            lua_string(&value.frame_variable)?
        )),
        BuiltinNodeArgs::GetColor(value) => Ok(format!(
            "__vars[{}] = Screen.getColor(__vars[{}],{},{})",
            lua_string(&value.result_variable)?,
            lua_string(&value.frame_variable)?,
            value.point.x,
            value.point.y
        )),
        BuiltinNodeArgs::FindColor(value) => render_find_color(value),
        BuiltinNodeArgs::CompareColor(value) => Ok(format!(
            "__vars[{}] = Screen.compareColor(__vars[{}],{},{},{},{})",
            lua_string(&value.result_variable)?,
            lua_string(&value.frame_variable)?,
            value.point.x,
            value.point.y,
            value.rgb,
            value.tolerance,
        )),
        BuiltinNodeArgs::FindMultiColor(value) => render_find_multi_color(value),
        BuiltinNodeArgs::CountColor(value) => {
            let region = &value.region;
            Ok(format!(
                "__vars[{}] = Screen.countColor(__vars[{}],{},{},{},{},{},{},{})",
                lua_string(&value.result_variable)?,
                lua_string(&value.frame_variable)?,
                value.rgb,
                value.tolerance,
                region.left,
                region.top,
                region.right,
                region.bottom,
                value.limit,
            ))
        }
        BuiltinNodeArgs::FindAllColor(value) => {
            let region = &value.region;
            Ok(format!(
                "__vars[{}] = Screen.findAllColor(__vars[{}],{},{},{},{},{},{},{})",
                lua_string(&value.result_variable)?,
                lua_string(&value.frame_variable)?,
                value.rgb,
                value.tolerance,
                region.left,
                region.top,
                region.right,
                region.bottom,
                value.limit,
            ))
        }
        BuiltinNodeArgs::FindImage(value) => render_find_image(value, key, false),
        BuiltinNodeArgs::GlyphOcr(value) => render_glyph_ocr(value),
        BuiltinNodeArgs::Gray(v) => {
            let r = &v.region;
            let frame = if v.auto_capture {
                "Screen.cache(Screen.capture())".into()
            } else {
                format!("__vars[{}]", lua_string(&v.frame_variable)?)
            };
            Ok(format!("do local __f={frame}; local __t=Screen.loadImage({}); local __r=Screen.findGray(__f,__t,{},{},{},{},{}); Screen.release(__t); {}; __vars[{}]=__r and 1 or 0; __vars[{}]=__r and __r.x or nil; __vars[{}]=__r and __r.y or nil; __vars[{}]=__r and __r.scorePermille or nil end",lua_string(&v.image_path)?,v.similarity_permille,r.left,r.top,r.right,r.bottom,if v.auto_capture {"Screen.release(__f)"} else {""},lua_string(&v.found_variable)?,lua_string(&v.x_variable)?,lua_string(&v.y_variable)?,lua_string(&v.score_variable)?))
        }
        BuiltinNodeArgs::Alphanumeric(v) => {
            let r = &v.region;
            let frame = if v.auto_capture {
                "Screen.cache(Screen.capture())".into()
            } else {
                format!("__vars[{}]", lua_string(&v.frame_variable)?)
            };
            Ok(format!("do local __f={frame}; local __r=Ocr.alphanumeric(__f,{},{},{},{},{}); {}; __vars[{}]=__r.text; __vars[{}]=__r.averageScorePermille end",r.left,r.top,r.right,r.bottom,v.minimum_confidence_permille,if v.auto_capture {"Screen.release(__f)"} else {""},lua_string(&v.text_variable)?,lua_string(&v.score_variable)?))
        }
        BuiltinNodeArgs::LegacyDuoDianZhaoSe(value) => render_legacy_duo_dian_zhao_se(value),
        BuiltinNodeArgs::LegacyDuoDianBiSe(value) => render_legacy_duo_dian_bi_se(value),
        BuiltinNodeArgs::LegacyGetRectColorNum(value) => render_legacy_get_rect_color_num(value),
        BuiltinNodeArgs::LegacyGetRgbColor(value) => Ok(format!(
            "__vars[{}] = Legacy.getRgbColor({},{},{})",
            lua_string(&value.result_variable)?,
            value.red,
            value.green,
            value.blue,
        )),
        BuiltinNodeArgs::If(_) | BuiltinNodeArgs::Repeat(_) | BuiltinNodeArgs::While(_) | BuiltinNodeArgs::LoopMetric(_) | BuiltinNodeArgs::LoopCheck(_) => {
            Err(invalid_builtin_variant())
        }
    }
}

fn legacy_color(rgb: u32) -> pixel_vision::Color {
    pixel_vision::Color {
        red: u8::try_from((rgb >> 16) & 0xFF).unwrap_or_default(),
        green: u8::try_from((rgb >> 8) & 0xFF).unwrap_or_default(),
        blue: u8::try_from(rgb & 0xFF).unwrap_or_default(),
        alpha: 255,
    }
}

const fn legacy_tolerance(red: u8, green: u8, blue: u8) -> pixel_vision::ColorTolerance {
    pixel_vision::ColorTolerance {
        red,
        green,
        blue,
        alpha: 0,
    }
}

fn legacy_format_error(kind: &str, error: &pixel_vision::LegacyFormatError) -> CompileError {
    CompileError::Serialization(format!(
        "{kind} cannot be encoded as legacy text: {error:?}"
    ))
}

/// Renders structured Flow data as the strict legacy parameter string at generation time, so the
/// author never edits the fragile old grammar by hand.
fn render_legacy_duo_dian_zhao_se(
    value: &crate::analyze::LegacyDuoDianZhaoSeArgs,
) -> Result<String, CompileError> {
    let samples = value
        .pattern
        .iter()
        .map(|sample| pixel_vision::PatternSample {
            offset_x: sample.dx,
            offset_y: sample.dy,
            color: legacy_color(sample.rgb),
            tolerance: legacy_tolerance(
                sample.tolerance_red,
                sample.tolerance_green,
                sample.tolerance_blue,
            ),
        })
        .collect::<Vec<_>>();
    let parameters = pixel_vision::format_relative_pattern(&samples)
        .map_err(|error| legacy_format_error("legacy.duodianzhaose", &error))?;
    let region = &value.region;
    Ok(format!(
        "do local __result = Legacy.duoDianZhaoSe(__vars[{}],{},{},{},{},{},{},{}); __vars[{}] = __result; __vars[{}] = __result.count; __vars[{}] = __result.count > 0; __vars[{}] = __result.first and __result.first.x or nil; __vars[{}] = __result.first and __result.first.y or nil end",
        lua_string(&value.frame_variable)?,
        region.left,
        region.top,
        region.width,
        region.height,
        lua_string(&parameters)?,
        value.direction,
        value.minimum_match_percent,
        lua_string(&value.result_variable)?,
        lua_string(&value.count_variable)?,
        lua_string(&value.found_variable)?,
        lua_string(&value.x_variable)?,
        lua_string(&value.y_variable)?,
    ))
}

fn render_legacy_duo_dian_bi_se(
    value: &crate::analyze::LegacyDuoDianBiSeArgs,
) -> Result<String, CompileError> {
    let samples = value
        .pattern
        .iter()
        .map(|sample| pixel_vision::FixedPatternSample {
            point: pixel_vision::PixelPoint {
                x: sample.x,
                y: sample.y,
            },
            color: legacy_color(sample.rgb),
            tolerance: legacy_tolerance(
                sample.tolerance_red,
                sample.tolerance_green,
                sample.tolerance_blue,
            ),
        })
        .collect::<Vec<_>>();
    let parameters = pixel_vision::format_fixed_pattern(&samples)
        .map_err(|error| legacy_format_error("legacy.duodianbise", &error))?;
    Ok(format!(
        "__vars[{}] = Legacy.duoDianBiSe(__vars[{}],{},{})",
        lua_string(&value.result_variable)?,
        lua_string(&value.frame_variable)?,
        lua_string(&parameters)?,
        value.minimum_match_percent,
    ))
}

fn render_legacy_get_rect_color_num(
    value: &crate::analyze::LegacyGetRectColorNumArgs,
) -> Result<String, CompileError> {
    let colors = value
        .colors
        .iter()
        .map(|color| pixel_vision::ColorSpec {
            color: legacy_color(color.rgb),
            tolerance: legacy_tolerance(
                color.tolerance_red,
                color.tolerance_green,
                color.tolerance_blue,
            ),
        })
        .collect::<Vec<_>>();
    let parameters = pixel_vision::format_color_list(&colors)
        .map_err(|error| legacy_format_error("legacy.getrectcolornum", &error))?;
    let region = &value.region;
    Ok(format!(
        "__vars[{}] = Legacy.getRectColorNum(__vars[{}],{},{},{},{},{})",
        lua_string(&value.result_variable)?,
        lua_string(&value.frame_variable)?,
        region.left,
        region.top,
        region.width,
        region.height,
        lua_string(&parameters)?,
    ))
}

fn render_find_multi_color(
    value: &crate::analyze::FindMultiColorArgs,
) -> Result<String, CompileError> {
    let samples = value
        .samples
        .iter()
        .map(|sample| {
            format!(
                "{{x={},y={},rgb={},tolerance={}}}",
                sample.x, sample.y, sample.rgb, sample.tolerance
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    let region = &value.region;
    Ok(format!(
        "do local __point = Screen.findMultiColor(__vars[{}],{},{},{{{}}},{},{},{},{}); __vars[{}] = __point ~= nil; __vars[{}] = __point and __point.x or nil; __vars[{}] = __point and __point.y or nil end",
        lua_string(&value.frame_variable)?,
        value.anchor_rgb,
        value.anchor_tolerance,
        samples,
        region.left,
        region.top,
        region.right,
        region.bottom,
        lua_string(&value.found_variable)?,
        lua_string(&value.x_variable)?,
        lua_string(&value.y_variable)?,
    ))
}

fn render_find_color(value: &crate::analyze::FindColorArgs) -> Result<String, CompileError> {
    let region = &value.region;
    Ok(format!(
        "do local __point = Screen.findColor(__vars[{}],{},{},{},{},{},{}); __vars[{}] = __point ~= nil; __vars[{}] = __point and __point.x or nil; __vars[{}] = __point and __point.y or nil end",
        lua_string(&value.frame_variable)?,
        value.rgb,
        value.tolerance,
        region.left,
        region.top,
        region.right,
        region.bottom,
        lua_string(&value.found_variable)?,
        lua_string(&value.x_variable)?,
        lua_string(&value.y_variable)?,
    ))
}

fn render_find_image(
    value: &crate::analyze::FindImageArgs,
    key: &str,
    numeric_found: bool,
) -> Result<String, CompileError> {
    let found_expression = if numeric_found {
        "__point and 1 or 0"
    } else {
        "__point ~= nil"
    };
    let region = &value.region;
    let edges = [region.left, region.top, region.right, region.bottom];
    let region_expressions = value
        .region_variables()
        .iter()
        .zip(edges)
        .map(|(variable, literal)| {
            variable.map_or_else(
                || Ok(literal.to_string()),
                |name| Ok(format!("__vars[{}]", lua_string(name)?)),
            )
        })
        .collect::<Result<Vec<String>, CompileError>>()?;
    let direction = if value.has_extended_options() {
        format!(",{}", value.direction)
    } else {
        String::new()
    };
    if value.has_extended_options() {
        let paths = if value.image_paths.is_empty() {
            vec![value.image_path.clone()]
        } else {
            value.image_paths.clone()
        };
        let paths_json = serde_json::to_string(&paths)
            .map_err(|error| CompileError::Serialization(error.to_string()))?;
        let frame = if value.auto_capture {
            "Screen.cache(Screen.capture())".to_owned()
        } else {
            format!("__vars[{}]", lua_string(&value.frame_variable)?)
        };
        let mut result = format!(
            "do local __recognize = __recognition_visit({}, {});",
            lua_string(key)?,
            value.frequency,
        );
        if let Some(name) = &value.image_variable {
            let variable = lua_string(name)?;
            result.push_str(&format!(" if __vars[{variable}] then Screen.release(__vars[{variable}]); __vars[{variable}] = nil end;"));
        }
        result.push_str(&format!(
            " local __point; if __recognize then local __frame = {frame}; __point = Screen.findImages(__frame,{},{},{},{},{},{},{},{});",
            lua_string(&paths_json)?, value.tolerance, value.similarity_permille,
            region_expressions[0],region_expressions[1],region_expressions[2],region_expressions[3],value.direction,
        ));
        if let Some(name) = &value.image_variable {
            result.push_str(&format!(" if __point then __vars[{}] = Screen.crop(__frame,__point.x,__point.y,__point.x+__point.width,__point.y+__point.height) end;",lua_string(name)?));
        }
        if value.auto_capture {
            result.push_str(" Screen.release(__frame);");
        }
        result.push_str(&format!(" end; __vars[{}] = {found_expression}; __vars[{}] = __point and __point.x or nil; __vars[{}] = __point and __point.y or nil;",
            lua_string(&value.found_variable)?,lua_string(&value.x_variable)?,lua_string(&value.y_variable)?,
        ));
        for (name, field) in [
            (value.template_variable.as_deref(), "path"),
            (value.score_variable.as_deref(), "scorePermille"),
        ] {
            if let Some(name) = name {
                result.push_str(&format!(
                    " __vars[{}] = __point and __point.{field} or nil;",
                    lua_string(name)?
                ));
            }
        }
        if value.success_action != crate::analyze::RecognitionAction::None {
            use crate::analyze::RecognitionAction;
            result.push_str(&format!(
                " if __point then local __x,__y=__point.x+({}),__point.y+({});",
                value.offset_x, value.offset_y
            ));
            match value.success_action {
                RecognitionAction::Tap => result.push_str(" Input.tapScreen(__x,__y);"),
                RecognitionAction::Hold => result.push_str(" Input.pointerDownScreen(__x,__y);"),
                RecognitionAction::TapWait => result.push_str(&format!(
                    " Input.tapScreen(__x,__y); Task.sleep({});",
                    value.action_duration_ms
                )),
                RecognitionAction::PressRelease => result.push_str(&format!(
                    " Input.pointerDownScreen(__x,__y); Task.sleep({}); Input.pointerUp();",
                    value.action_duration_ms
                )),
                RecognitionAction::None => {}
            }
            result.push_str(" end;");
        }
        result.push_str(" end");
        return Ok(result);
    }
    Ok(format!(
        "do local __template = Screen.loadImage({}); local __point = Screen.findImage(__vars[{}],__template,{},{},{},{},{},{}{}); Screen.release(__template); __vars[{}] = {found_expression}; __vars[{}] = __point and __point.x or nil; __vars[{}] = __point and __point.y or nil end",
        lua_string(&value.image_path)?,
        lua_string(&value.frame_variable)?,
        value.tolerance,
        value.similarity_permille,
        region_expressions[0],
        region_expressions[1],
        region_expressions[2],
        region_expressions[3],
        direction,
        lua_string(&value.found_variable)?,
        lua_string(&value.x_variable)?,
        lua_string(&value.y_variable)?,
    ))
}

fn render_glyph_ocr(value: &crate::analyze::GlyphOcrArgs) -> Result<String, CompileError> {
    let region = &value.region;
    Ok(format!(
        "do local __dictionary = Ocr.loadDictionary({}); local __result = Ocr.glyph(__vars[{}],__dictionary,{},{},{},{},{},{},{},{}); Ocr.releaseDictionary(__dictionary); __vars[{}] = __result.text; __vars[{}] = __result.coveragePermille; __vars[{}] = __result.averageScorePermille end",
        lua_string(&value.dictionary_path)?,
        lua_string(&value.frame_variable)?,
        value.foreground_rgb,
        value.tolerance,
        value.similarity_permille,
        region.left,
        region.top,
        region.right,
        region.bottom,
        value.space_gap_columns,
        lua_string(&value.text_variable)?,
        lua_string(&value.coverage_variable)?,
        lua_string(&value.score_variable)?,
    ))
}

fn render_comparison(arguments: &crate::analyze::ComparisonArgs) -> Result<String, CompileError> {
    comparison_expression(
        &arguments.variable,
        arguments.operator,
        &arguments.value,
        arguments.value_variable.as_deref(),
    )
}

fn render_while_comparison(arguments: &crate::analyze::WhileArgs) -> Result<String, CompileError> {
    comparison_expression(
        &arguments.variable,
        arguments.operator,
        &arguments.value,
        None,
    )
}

fn comparison_expression(
    variable: &str,
    operator: ComparisonOperator,
    value: &Value,
    value_variable: Option<&str>,
) -> Result<String, CompileError> {
    let right = match value_variable {
        Some(name) => format!("__vars[{}]", lua_string(name)?),
        None => lua_literal(value)?,
    };
    Ok(format!(
        "__compare(__vars[{}],{}, {})",
        lua_string(variable)?,
        lua_string(comparison_operator(operator))?,
        right
    ))
}

const fn comparison_operator(operator: ComparisonOperator) -> &'static str {
    match operator {
        ComparisonOperator::Equals => "equals",
        ComparisonOperator::NotEquals => "notEquals",
        ComparisonOperator::LessThan => "lessThan",
        ComparisonOperator::LessOrEqual => "lessOrEqual",
        ComparisonOperator::GreaterThan => "greaterThan",
        ComparisonOperator::GreaterOrEqual => "greaterOrEqual",
    }
}

fn invalid_builtin_variant() -> CompileError {
    CompileError::Serialization("validated builtin node has the wrong argument variant".into())
}

pub(crate) fn render_source_map(
    generation_id: &str,
    entries: Vec<SourceMapEntry>,
) -> Result<Vec<u8>, CompileError> {
    let source_map = SourceMap {
        schema_version: 1,
        generation_id: generation_id.to_owned(),
        entries,
    };
    pretty_json(&source_map)
}

pub(crate) fn pretty_json(value: &impl serde::Serialize) -> Result<Vec<u8>, CompileError> {
    let mut output = serde_json::to_vec_pretty(value)
        .map_err(|error| CompileError::Serialization(error.to_string()))?;
    output.push(b'\n');
    Ok(output)
}

fn render_call(project: &PreparedProject<'_>, call: &FlowCallArgs) -> Result<String, CompileError> {
    Ok(format!(
        "__flows[{}]({})",
        lua_string(&call.target_flow_id)?,
        render_call_payload(project, call)?
    ))
}

fn render_call_payload(
    project: &PreparedProject<'_>,
    call: &FlowCallArgs,
) -> Result<String, CompileError> {
    let target = project
        .flows
        .iter()
        .find(|flow| flow.declaration.flow_id == call.target_flow_id)
        .ok_or_else(|| CompileError::Serialization("validated target Flow is missing".into()))?;
    let mut arguments = Vec::with_capacity(call.arguments.len());
    for (name, value) in &call.arguments {
        arguments.push(format!("[{}]={}", lua_string(name)?, lua_literal(value)?));
    }
    let mut names = Vec::with_capacity(target.declaration.params.len());
    for (index, parameter) in target.declaration.params.iter().enumerate() {
        names.push(format!("[{}]={}", index + 1, lua_string(&parameter.name)?));
    }
    Ok(format!(
        "(function() local __payload={{{}}}; local __names={{{}}}; for __i,__name in pairs(__names) do __payload[__i]=__payload[__name] end; for __i,__v in pairs(__call_args) do __payload[__i]=__v; local __name=__names[__i]; if __name then __payload[__name]=__v end end; __call_args = {{}}; return __payload end)()",
        arguments.join(","),
        names.join(",")
    ))
}

fn lua_literal(value: &Value) -> Result<String, CompileError> {
    match value {
        Value::Bool(_) | Value::Number(_) | Value::String(_) => serde_json::to_string(value)
            .map_err(|error| CompileError::Serialization(error.to_string())),
        Value::Null => Ok("nil".into()),
        Value::Array(_) | Value::Object(_) => Err(CompileError::Serialization(
            "generated Lua values must be scalar literals".into(),
        )),
    }
}

fn lua_string(value: &str) -> Result<String, CompileError> {
    serde_json::to_string(value).map_err(|error| CompileError::Serialization(error.to_string()))
}

#[derive(Default)]
struct LuaWriter {
    output: String,
    lines: u32,
}

impl LuaWriter {
    fn line(&mut self, value: &str) {
        self.output.push_str(value);
        self.output.push('\n');
        self.lines += 1;
    }

    fn indented(&mut self, indent: usize, value: &str) {
        self.output.push_str(&"  ".repeat(indent));
        self.line(value);
    }

    const fn next_line(&self) -> u32 {
        self.lines + 1
    }

    const fn current_line(&self) -> u32 {
        self.lines
    }
}

#[cfg(test)]
mod tests {
    use super::lua_literal;
    use serde_json::json;

    #[test]
    fn lua_string_literal_escapes_control_characters() {
        assert_eq!(lua_literal(&json!("a\nb")).as_deref(), Ok("\"a\\nb\""));
    }
}
