use crate::analyze::{BuiltinNodeArgs, ComparisonOperator, FlowCallArgs, PreparedProject};
use crate::model::{CompileError, SourceMap, SourceMapEntry};
use serde_json::Value;
use std::collections::HashMap;

pub(crate) fn render_lua(
    project: &PreparedProject<'_>,
    entry_flow_id: &str,
    generation_id: &str,
) -> Result<(Vec<u8>, Vec<SourceMapEntry>), CompileError> {
    let mut writer = LuaWriter::default();
    writer.line("-- @generated by flow-compiler; do not edit.");
    writer.line(&format!("-- generationId: {generation_id}"));
    writer.line("local __flows = {}");
    writer.line("local function __compare(left, operator, right)");
    writer.line("  if operator == \"equals\" then return left == right end");
    writer.line("  if operator == \"notEquals\" then return left ~= right end");
    writer.line("  local kind = type(left)");
    writer.line("  if kind ~= type(right) or (kind ~= \"number\" and kind ~= \"string\") then return false end");
    writer.line("  if operator == \"lessThan\" then return left < right end");
    writer.line("  if operator == \"lessOrEqual\" then return left <= right end");
    writer.line("  if operator == \"greaterThan\" then return left > right end");
    writer.line("  if operator == \"greaterOrEqual\" then return left >= right end");
    writer.line("  return false");
    writer.line("end");
    let mut entries = Vec::new();
    for flow in &project.flows {
        writer.line("");
        writer.line(&format!(
            "__flows[{}] = function(__args)",
            lua_string(&flow.declaration.flow_id)?
        ));
        writer.line("  __args = __args or {}");
        writer.line("  local __vars = {}");
        for parameter in &flow.declaration.params {
            writer.line(&format!(
                "  __vars[{}] = __args[{}]",
                lua_string(&parameter.name)?,
                lua_string(&parameter.name)?
            ));
        }
        let canonical_nodes = flow
            .document
            .canonical_nodes()
            .ok_or_else(|| CompileError::Serialization("missing canonical node order".into()))?
            .collect::<Vec<_>>();
        let mut blocks: HashMap<&str, Vec<&flow_ir::FlowNode>> = HashMap::new();
        for node in canonical_nodes {
            blocks
                .entry(node.envelope.block_id.as_str())
                .or_default()
                .push(node);
        }
        render_flow_body(
            project,
            &flow.declaration.flow_id,
            &flow.document.root_block_id,
            &blocks,
            &mut writer,
            &mut entries,
        )?;
        writer.line("end");
    }
    writer.line("");
    writer.line("return function(__entry_args)");
    writer.line(&format!(
        "  return __flows[{}](__entry_args or {{}})",
        lua_string(entry_flow_id)?
    ));
    writer.line("end");
    Ok((writer.output.into_bytes(), entries))
}

enum RenderEvent<'a> {
    Block(&'a str, usize),
    Node(&'a flow_ir::FlowNode, usize),
    Line(usize, &'static str),
    OwnedLine(usize, String),
}

fn render_flow_body<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    root_block_id: &'a str,
    blocks: &HashMap<&'a str, Vec<&'a flow_ir::FlowNode>>,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
) -> Result<(), CompileError> {
    let mut events = vec![RenderEvent::Block(root_block_id, 1)];
    while let Some(event) = events.pop() {
        match event {
            RenderEvent::Line(indent, line) => writer.indented(indent, line),
            RenderEvent::OwnedLine(indent, line) => writer.indented(indent, &line),
            RenderEvent::Block(block_id, indent) => {
                for node in blocks.get(block_id).into_iter().flatten().rev() {
                    events.push(RenderEvent::Node(node, indent));
                }
            }
            RenderEvent::Node(node, indent) => {
                render_node(project, flow_id, node, indent, writer, entries, &mut events)?;
            }
        }
    }
    Ok(())
}

fn render_node<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    node: &'a flow_ir::FlowNode,
    indent: usize,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
    events: &mut Vec<RenderEvent<'a>>,
) -> Result<(), CompileError> {
    let kind = node.envelope.kind.as_str();
    match kind {
        "task.noop" => {
            writer.indented(indent, "do end");
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "flow.call" => {
            let call = project.calls.get(&node.envelope.node_id).ok_or_else(|| {
                CompileError::Serialization("validated flow.call is missing".into())
            })?;
            writer.indented(indent, &render_call(call)?);
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "task.sleep"
        | "task.log"
        | "input.tap"
        | "input.swipe"
        | "input.keyevent"
        | "variable.set"
        | "variable.copy"
        | "screen.capture"
        | "screen.release"
        | "vision.getcolor"
        | "vision.findcolor"
        | "vision.comparecolor"
        | "vision.findmulticolor"
        | "vision.countcolor"
        | "vision.findallcolor"
        | "vision.findimage"
        | "ocr.glyph"
        | "legacy.duodianzhaose"
        | "legacy.duodianbise"
        | "legacy.getrectcolornum"
        | "legacy.getrgbcolor" => {
            let arguments = builtin_arguments(project, node)?;
            writer.indented(indent, &render_builtin(arguments)?);
            push_source_entry(
                flow_id,
                node,
                writer.current_line(),
                writer.current_line(),
                entries,
            );
        }
        "control.if" => render_if(project, flow_id, node, indent, writer, entries, events)?,
        "control.repeat" => {
            render_repeat(project, flow_id, node, indent, writer, entries, events)?;
        }
        "control.while" => {
            render_while(project, flow_id, node, indent, writer, entries, events)?;
        }
        _ => {
            return Err(CompileError::UnsupportedNodeKind {
                node_id: node.envelope.node_id.clone(),
                kind: kind.to_owned(),
            });
        }
    }
    Ok(())
}

fn render_if<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    node: &'a flow_ir::FlowNode,
    indent: usize,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
    events: &mut Vec<RenderEvent<'a>>,
) -> Result<(), CompileError> {
    let BuiltinNodeArgs::If(arguments) = builtin_arguments(project, node)? else {
        return Err(invalid_builtin_variant());
    };
    writer.indented(
        indent,
        &format!("if {} then", render_comparison(arguments)?),
    );
    push_source_entry(
        flow_id,
        node,
        writer.current_line(),
        writer.current_line(),
        entries,
    );
    events.push(RenderEvent::Line(indent, "end"));
    events.push(RenderEvent::Block(child_block(node, "else")?, indent + 1));
    events.push(RenderEvent::Line(indent, "else"));
    for (index, branch) in arguments.else_if.iter().enumerate().rev() {
        events.push(RenderEvent::Block(
            child_block(node, &format!("elseIf{index}"))?,
            indent + 1,
        ));
        events.push(RenderEvent::OwnedLine(
            indent,
            format!(
                "elseif {} then",
                comparison_expression(
                    &branch.variable,
                    branch.operator,
                    &branch.value,
                    branch.value_variable.as_deref(),
                )?
            ),
        ));
    }
    events.push(RenderEvent::Block(child_block(node, "then")?, indent + 1));
    Ok(())
}

fn render_repeat<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    node: &'a flow_ir::FlowNode,
    indent: usize,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
    events: &mut Vec<RenderEvent<'a>>,
) -> Result<(), CompileError> {
    let BuiltinNodeArgs::Repeat(arguments) = builtin_arguments(project, node)? else {
        return Err(invalid_builtin_variant());
    };
    writer.indented(indent, "do");
    writer.indented(
        indent + 1,
        "local __loop_started_at = System.elapsedRealtimeMillis()",
    );
    writer.indented(indent + 1, "local __loop_count = 0");
    if let Some(name) = &arguments.times_variable {
        writer.indented(
            indent + 1,
            &format!("local __loop_times = __vars[{}]", lua_string(name)?),
        );
        writer.indented(indent + 1, "if type(__loop_times) ~= \"number\" or __loop_times % 1 ~= 0 or __loop_times < 0 or __loop_times > 1000000 then error(\"control.repeat timesVariable is invalid\", 0) end");
    } else {
        writer.indented(
            indent + 1,
            &format!("local __loop_times = {}", arguments.times),
        );
    }
    let start = writer.next_line();
    writer.indented(indent + 1, "for __index = 1, __loop_times do");
    writer.indented(indent + 2, "__loop_count = __index");
    if let Some(name) = &arguments.index_variable {
        writer.indented(
            indent + 2,
            &format!("__vars[{}] = __index", lua_string(name)?),
        );
    }
    if let Some(name) = &arguments.elapsed_variable {
        writer.indented(
            indent + 2,
            &format!(
                "__vars[{}] = System.elapsedRealtimeMillis() - __loop_started_at",
                lua_string(name)?
            ),
        );
    }
    push_source_entry(flow_id, node, start, writer.current_line(), entries);
    events.push(RenderEvent::Line(indent, "end"));
    events.push(RenderEvent::Line(indent + 1, "end"));
    events.push(RenderEvent::Block(child_block(node, "body")?, indent + 2));
    Ok(())
}

fn render_while<'a>(
    project: &PreparedProject<'a>,
    flow_id: &str,
    node: &'a flow_ir::FlowNode,
    indent: usize,
    writer: &mut LuaWriter,
    entries: &mut Vec<SourceMapEntry>,
    events: &mut Vec<RenderEvent<'a>>,
) -> Result<(), CompileError> {
    let BuiltinNodeArgs::While(arguments) = builtin_arguments(project, node)? else {
        return Err(invalid_builtin_variant());
    };
    writer.indented(indent, "do");
    writer.indented(indent + 1, "local __iterations = 0");
    writer.indented(
        indent + 1,
        "local __loop_started_at = System.elapsedRealtimeMillis()",
    );
    if let Some(name) = &arguments.duration_variable {
        writer.indented(
            indent + 1,
            &format!("local __loop_duration = __vars[{}]", lua_string(name)?),
        );
        writer.indented(indent + 1, "if type(__loop_duration) ~= \"number\" or __loop_duration <= 0 then error(\"control.while durationVariable is invalid\", 0) end");
    } else if let Some(duration) = arguments.duration_ms {
        writer.indented(indent + 1, &format!("local __loop_duration = {duration}"));
    }
    let start = writer.next_line();
    writer.indented(
        indent + 1,
        &format!(
            "while {}{} do",
            if arguments.always {
                "true".to_owned()
            } else {
                render_while_comparison(arguments)?
            },
            if arguments.duration_ms.is_some() || arguments.duration_variable.is_some() {
                " and System.elapsedRealtimeMillis() - __loop_started_at < __loop_duration"
            } else {
                ""
            }
        ),
    );
    writer.indented(indent + 2, "__iterations = __iterations + 1");
    if let Some(name) = &arguments.iteration_variable {
        writer.indented(
            indent + 2,
            &format!("__vars[{}] = __iterations", lua_string(name)?),
        );
    }
    if let Some(name) = &arguments.elapsed_variable {
        writer.indented(
            indent + 2,
            &format!(
                "__vars[{}] = System.elapsedRealtimeMillis() - __loop_started_at",
                lua_string(name)?
            ),
        );
    }
    writer.indented(
        indent + 2,
        &format!(
            "if __iterations > {} then error(\"control.while iteration limit exceeded\", 0) end",
            arguments.max_iterations
        ),
    );
    push_source_entry(flow_id, node, start, writer.current_line(), entries);
    events.push(RenderEvent::Line(indent, "end"));
    events.push(RenderEvent::Line(indent + 1, "end"));
    events.push(RenderEvent::Block(child_block(node, "body")?, indent + 2));
    Ok(())
}

fn builtin_arguments<'a>(
    project: &'a PreparedProject<'_>,
    node: &flow_ir::FlowNode,
) -> Result<&'a BuiltinNodeArgs, CompileError> {
    project
        .builtins
        .get(&node.envelope.node_id)
        .ok_or_else(|| CompileError::Serialization("validated builtin node is missing".into()))
}

fn child_block<'a>(node: &'a flow_ir::FlowNode, name: &str) -> Result<&'a str, CompileError> {
    node.envelope
        .child_blocks
        .get(name)
        .map(String::as_str)
        .ok_or_else(|| CompileError::Serialization("validated child block is missing".into()))
}

fn push_source_entry(
    flow_id: &str,
    node: &flow_ir::FlowNode,
    start: u32,
    end: u32,
    entries: &mut Vec<SourceMapEntry>,
) {
    entries.push(SourceMapEntry {
        flow_id: flow_id.to_owned(),
        node_id: node.envelope.node_id.clone(),
        lua_start_line: start,
        lua_end_line: end,
    });
}

fn render_builtin(arguments: &BuiltinNodeArgs) -> Result<String, CompileError> {
    match arguments {
        BuiltinNodeArgs::Sleep(value) => Ok(format!("Task.sleep({})", value.milliseconds)),
        BuiltinNodeArgs::Log(value) => {
            let level = match value.level {
                crate::analyze::LogLevel::Info => "info",
                crate::analyze::LogLevel::Warn => "warn",
                crate::analyze::LogLevel::Error => "error",
            };
            Ok(format!("Log.{level}({})", lua_string(&value.message)?))
        }
        BuiltinNodeArgs::Tap(value) => Ok(format!("Input.tap({},{})", value.x, value.y)),
        BuiltinNodeArgs::Swipe(value) => Ok(format!(
            "Input.swipe({},{},{},{},{})",
            value.x1, value.y1, value.x2, value.y2, value.duration_ms
        )),
        BuiltinNodeArgs::KeyEvent(value) => Ok(format!("Input.keyEvent({})", value.key_code)),
        BuiltinNodeArgs::VariableSet(value) => Ok(format!(
            "__vars[{}] = {}",
            lua_string(&value.name)?,
            lua_literal(&value.value)?
        )),
        BuiltinNodeArgs::VariableCopy(value) => Ok(format!(
            "__vars[{}] = __vars[{}]",
            lua_string(&value.name)?,
            lua_string(&value.source_name)?
        )),
        BuiltinNodeArgs::ScreenCapture(value) => Ok(format!(
            "__vars[{}] = Screen.cache(Screen.capture())",
            lua_string(&value.result_variable)?
        )),
        BuiltinNodeArgs::ScreenRelease(value) => Ok(format!(
            "Screen.release(__vars[{}]); __vars[{}] = nil",
            lua_string(&value.frame_variable)?,
            lua_string(&value.frame_variable)?
        )),
        BuiltinNodeArgs::GetColor(value) => Ok(format!(
            "__vars[{}] = Screen.getColor(__vars[{}],{},{})",
            lua_string(&value.result_variable)?,
            lua_string(&value.frame_variable)?,
            value.point.x,
            value.point.y
        )),
        BuiltinNodeArgs::FindColor(value) => render_find_color(value),
        BuiltinNodeArgs::CompareColor(value) => Ok(format!(
            "__vars[{}] = Screen.compareColor(__vars[{}],{},{},{},{})",
            lua_string(&value.result_variable)?,
            lua_string(&value.frame_variable)?,
            value.point.x,
            value.point.y,
            value.rgb,
            value.tolerance,
        )),
        BuiltinNodeArgs::FindMultiColor(value) => render_find_multi_color(value),
        BuiltinNodeArgs::CountColor(value) => {
            let region = &value.region;
            Ok(format!(
                "__vars[{}] = Screen.countColor(__vars[{}],{},{},{},{},{},{},{})",
                lua_string(&value.result_variable)?,
                lua_string(&value.frame_variable)?,
                value.rgb,
                value.tolerance,
                region.left,
                region.top,
                region.right,
                region.bottom,
                value.limit,
            ))
        }
        BuiltinNodeArgs::FindAllColor(value) => {
            let region = &value.region;
            Ok(format!(
                "__vars[{}] = Screen.findAllColor(__vars[{}],{},{},{},{},{},{},{})",
                lua_string(&value.result_variable)?,
                lua_string(&value.frame_variable)?,
                value.rgb,
                value.tolerance,
                region.left,
                region.top,
                region.right,
                region.bottom,
                value.limit,
            ))
        }
        BuiltinNodeArgs::FindImage(value) => render_find_image(value),
        BuiltinNodeArgs::GlyphOcr(value) => render_glyph_ocr(value),
        BuiltinNodeArgs::LegacyDuoDianZhaoSe(value) => render_legacy_duo_dian_zhao_se(value),
        BuiltinNodeArgs::LegacyDuoDianBiSe(value) => render_legacy_duo_dian_bi_se(value),
        BuiltinNodeArgs::LegacyGetRectColorNum(value) => render_legacy_get_rect_color_num(value),
        BuiltinNodeArgs::LegacyGetRgbColor(value) => Ok(format!(
            "__vars[{}] = Legacy.getRgbColor({},{},{})",
            lua_string(&value.result_variable)?,
            value.red,
            value.green,
            value.blue,
        )),
        BuiltinNodeArgs::If(_) | BuiltinNodeArgs::Repeat(_) | BuiltinNodeArgs::While(_) => {
            Err(invalid_builtin_variant())
        }
    }
}

fn legacy_color(rgb: u32) -> pixel_vision::Color {
    pixel_vision::Color {
        red: u8::try_from((rgb >> 16) & 0xFF).unwrap_or_default(),
        green: u8::try_from((rgb >> 8) & 0xFF).unwrap_or_default(),
        blue: u8::try_from(rgb & 0xFF).unwrap_or_default(),
        alpha: 255,
    }
}

const fn legacy_tolerance(red: u8, green: u8, blue: u8) -> pixel_vision::ColorTolerance {
    pixel_vision::ColorTolerance {
        red,
        green,
        blue,
        alpha: 0,
    }
}

fn legacy_format_error(kind: &str, error: &pixel_vision::LegacyFormatError) -> CompileError {
    CompileError::Serialization(format!(
        "{kind} cannot be encoded as legacy text: {error:?}"
    ))
}

/// Renders structured Flow data as the strict legacy parameter string at generation time, so the
/// author never edits the fragile old grammar by hand.
fn render_legacy_duo_dian_zhao_se(
    value: &crate::analyze::LegacyDuoDianZhaoSeArgs,
) -> Result<String, CompileError> {
    let samples = value
        .pattern
        .iter()
        .map(|sample| pixel_vision::PatternSample {
            offset_x: sample.dx,
            offset_y: sample.dy,
            color: legacy_color(sample.rgb),
            tolerance: legacy_tolerance(
                sample.tolerance_red,
                sample.tolerance_green,
                sample.tolerance_blue,
            ),
        })
        .collect::<Vec<_>>();
    let parameters = pixel_vision::format_relative_pattern(&samples)
        .map_err(|error| legacy_format_error("legacy.duodianzhaose", &error))?;
    let region = &value.region;
    Ok(format!(
        "do local __result = Legacy.duoDianZhaoSe(__vars[{}],{},{},{},{},{},{},{}); __vars[{}] = __result; __vars[{}] = __result.count; __vars[{}] = __result.count > 0; __vars[{}] = __result.first and __result.first.x or nil; __vars[{}] = __result.first and __result.first.y or nil end",
        lua_string(&value.frame_variable)?,
        region.left,
        region.top,
        region.width,
        region.height,
        lua_string(&parameters)?,
        value.direction,
        value.minimum_match_percent,
        lua_string(&value.result_variable)?,
        lua_string(&value.count_variable)?,
        lua_string(&value.found_variable)?,
        lua_string(&value.x_variable)?,
        lua_string(&value.y_variable)?,
    ))
}

fn render_legacy_duo_dian_bi_se(
    value: &crate::analyze::LegacyDuoDianBiSeArgs,
) -> Result<String, CompileError> {
    let samples = value
        .pattern
        .iter()
        .map(|sample| pixel_vision::FixedPatternSample {
            point: pixel_vision::PixelPoint {
                x: sample.x,
                y: sample.y,
            },
            color: legacy_color(sample.rgb),
            tolerance: legacy_tolerance(
                sample.tolerance_red,
                sample.tolerance_green,
                sample.tolerance_blue,
            ),
        })
        .collect::<Vec<_>>();
    let parameters = pixel_vision::format_fixed_pattern(&samples)
        .map_err(|error| legacy_format_error("legacy.duodianbise", &error))?;
    Ok(format!(
        "__vars[{}] = Legacy.duoDianBiSe(__vars[{}],{},{})",
        lua_string(&value.result_variable)?,
        lua_string(&value.frame_variable)?,
        lua_string(&parameters)?,
        value.minimum_match_percent,
    ))
}

fn render_legacy_get_rect_color_num(
    value: &crate::analyze::LegacyGetRectColorNumArgs,
) -> Result<String, CompileError> {
    let colors = value
        .colors
        .iter()
        .map(|color| pixel_vision::ColorSpec {
            color: legacy_color(color.rgb),
            tolerance: legacy_tolerance(
                color.tolerance_red,
                color.tolerance_green,
                color.tolerance_blue,
            ),
        })
        .collect::<Vec<_>>();
    let parameters = pixel_vision::format_color_list(&colors)
        .map_err(|error| legacy_format_error("legacy.getrectcolornum", &error))?;
    let region = &value.region;
    Ok(format!(
        "__vars[{}] = Legacy.getRectColorNum(__vars[{}],{},{},{},{},{})",
        lua_string(&value.result_variable)?,
        lua_string(&value.frame_variable)?,
        region.left,
        region.top,
        region.width,
        region.height,
        lua_string(&parameters)?,
    ))
}

fn render_find_multi_color(
    value: &crate::analyze::FindMultiColorArgs,
) -> Result<String, CompileError> {
    let samples = value
        .samples
        .iter()
        .map(|sample| {
            format!(
                "{{x={},y={},rgb={},tolerance={}}}",
                sample.x, sample.y, sample.rgb, sample.tolerance
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    let region = &value.region;
    Ok(format!(
        "do local __point = Screen.findMultiColor(__vars[{}],{},{},{{{}}},{},{},{},{}); __vars[{}] = __point ~= nil; __vars[{}] = __point and __point.x or nil; __vars[{}] = __point and __point.y or nil end",
        lua_string(&value.frame_variable)?,
        value.anchor_rgb,
        value.anchor_tolerance,
        samples,
        region.left,
        region.top,
        region.right,
        region.bottom,
        lua_string(&value.found_variable)?,
        lua_string(&value.x_variable)?,
        lua_string(&value.y_variable)?,
    ))
}

fn render_find_color(value: &crate::analyze::FindColorArgs) -> Result<String, CompileError> {
    let region = &value.region;
    Ok(format!(
        "do local __point = Screen.findColor(__vars[{}],{},{},{},{},{},{}); __vars[{}] = __point ~= nil; __vars[{}] = __point and __point.x or nil; __vars[{}] = __point and __point.y or nil end",
        lua_string(&value.frame_variable)?,
        value.rgb,
        value.tolerance,
        region.left,
        region.top,
        region.right,
        region.bottom,
        lua_string(&value.found_variable)?,
        lua_string(&value.x_variable)?,
        lua_string(&value.y_variable)?,
    ))
}

fn render_find_image(value: &crate::analyze::FindImageArgs) -> Result<String, CompileError> {
    let region = &value.region;
    Ok(format!(
        "do local __template = Screen.loadImage({}); local __point = Screen.findImage(__vars[{}],__template,{},{},{},{},{},{}); Screen.release(__template); __vars[{}] = __point ~= nil; __vars[{}] = __point and __point.x or nil; __vars[{}] = __point and __point.y or nil end",
        lua_string(&value.image_path)?,
        lua_string(&value.frame_variable)?,
        value.tolerance,
        value.similarity_permille,
        region.left,
        region.top,
        region.right,
        region.bottom,
        lua_string(&value.found_variable)?,
        lua_string(&value.x_variable)?,
        lua_string(&value.y_variable)?,
    ))
}

fn render_glyph_ocr(value: &crate::analyze::GlyphOcrArgs) -> Result<String, CompileError> {
    let region = &value.region;
    Ok(format!(
        "do local __dictionary = Ocr.loadDictionary({}); local __result = Ocr.glyph(__vars[{}],__dictionary,{},{},{},{},{},{},{},{}); Ocr.releaseDictionary(__dictionary); __vars[{}] = __result.text; __vars[{}] = __result.coveragePermille; __vars[{}] = __result.averageScorePermille end",
        lua_string(&value.dictionary_path)?,
        lua_string(&value.frame_variable)?,
        value.foreground_rgb,
        value.tolerance,
        value.similarity_permille,
        region.left,
        region.top,
        region.right,
        region.bottom,
        value.space_gap_columns,
        lua_string(&value.text_variable)?,
        lua_string(&value.coverage_variable)?,
        lua_string(&value.score_variable)?,
    ))
}

fn render_comparison(arguments: &crate::analyze::ComparisonArgs) -> Result<String, CompileError> {
    comparison_expression(
        &arguments.variable,
        arguments.operator,
        &arguments.value,
        arguments.value_variable.as_deref(),
    )
}

fn render_while_comparison(arguments: &crate::analyze::WhileArgs) -> Result<String, CompileError> {
    comparison_expression(
        &arguments.variable,
        arguments.operator,
        &arguments.value,
        None,
    )
}

fn comparison_expression(
    variable: &str,
    operator: ComparisonOperator,
    value: &Value,
    value_variable: Option<&str>,
) -> Result<String, CompileError> {
    let right = match value_variable {
        Some(name) => format!("__vars[{}]", lua_string(name)?),
        None => lua_literal(value)?,
    };
    Ok(format!(
        "__compare(__vars[{}],{}, {})",
        lua_string(variable)?,
        lua_string(comparison_operator(operator))?,
        right
    ))
}

const fn comparison_operator(operator: ComparisonOperator) -> &'static str {
    match operator {
        ComparisonOperator::Equals => "equals",
        ComparisonOperator::NotEquals => "notEquals",
        ComparisonOperator::LessThan => "lessThan",
        ComparisonOperator::LessOrEqual => "lessOrEqual",
        ComparisonOperator::GreaterThan => "greaterThan",
        ComparisonOperator::GreaterOrEqual => "greaterOrEqual",
    }
}

fn invalid_builtin_variant() -> CompileError {
    CompileError::Serialization("validated builtin node has the wrong argument variant".into())
}

pub(crate) fn render_source_map(
    generation_id: &str,
    entries: Vec<SourceMapEntry>,
) -> Result<Vec<u8>, CompileError> {
    let source_map = SourceMap {
        schema_version: 1,
        generation_id: generation_id.to_owned(),
        entries,
    };
    pretty_json(&source_map)
}

pub(crate) fn pretty_json(value: &impl serde::Serialize) -> Result<Vec<u8>, CompileError> {
    let mut output = serde_json::to_vec_pretty(value)
        .map_err(|error| CompileError::Serialization(error.to_string()))?;
    output.push(b'\n');
    Ok(output)
}

fn render_call(call: &FlowCallArgs) -> Result<String, CompileError> {
    let mut arguments = Vec::with_capacity(call.arguments.len());
    for (name, value) in &call.arguments {
        arguments.push(format!("[{}]={}", lua_string(name)?, lua_literal(value)?));
    }
    Ok(format!(
        "__flows[{}]({{{}}})",
        lua_string(&call.target_flow_id)?,
        arguments.join(",")
    ))
}

fn lua_literal(value: &Value) -> Result<String, CompileError> {
    match value {
        Value::Bool(_) | Value::Number(_) | Value::String(_) => serde_json::to_string(value)
            .map_err(|error| CompileError::Serialization(error.to_string())),
        Value::Null => Ok("nil".into()),
        Value::Array(_) | Value::Object(_) => Err(CompileError::Serialization(
            "generated Lua values must be scalar literals".into(),
        )),
    }
}

fn lua_string(value: &str) -> Result<String, CompileError> {
    serde_json::to_string(value).map_err(|error| CompileError::Serialization(error.to_string()))
}

#[derive(Default)]
struct LuaWriter {
    output: String,
    lines: u32,
}

impl LuaWriter {
    fn line(&mut self, value: &str) {
        self.output.push_str(value);
        self.output.push('\n');
        self.lines += 1;
    }

    fn indented(&mut self, indent: usize, value: &str) {
        self.output.push_str(&"  ".repeat(indent));
        self.line(value);
    }

    const fn next_line(&self) -> u32 {
        self.lines + 1
    }

    const fn current_line(&self) -> u32 {
        self.lines
    }
}

#[cfg(test)]
mod tests {
    use super::lua_literal;
    use serde_json::json;

    #[test]
    fn lua_string_literal_escapes_control_characters() {
        assert_eq!(lua_literal(&json!("a\nb")).as_deref(), Ok("\"a\\nb\""));
    }
}
