use crate::digest::content_digest;
use crate::model::{CommitError, GenerationBundle, GenerationRecord, SourceMap};
use fs4::TryLockError;
use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

const LOCK_FILE: &str = ".generation.lock";

/// Commits a complete generation in fail-closed order inside one filesystem directory.
///
/// All temporary files are written and synced first. `main.lua` and `source-map.json` are replaced
/// before `generation.json`, so the authoritative record never accepts a mixed generation.
///
/// # Errors
///
/// Returns an error when another writer owns the lock, the public bundle was modified after
/// compilation, or a filesystem operation fails.
pub fn commit_generation(
    generated_directory: &Path,
    bundle: &GenerationBundle,
) -> Result<(), CommitError> {
    validate_bundle(bundle)?;
    fs::create_dir_all(generated_directory)
        .map_err(|error| io_error("create generated directory", generated_directory, &error))?;
    let lock = CommitLock::acquire(generated_directory)?;
    let suffix = &bundle.record.generation_id;
    let specifications = [
        (
            format!(".main.lua.{suffix}.tmp"),
            bundle.main_lua.as_slice(),
        ),
        (
            format!(".source-map.json.{suffix}.tmp"),
            bundle.source_map_json.as_slice(),
        ),
        (
            format!(".generation.json.{suffix}.tmp"),
            bundle.generation_json.as_slice(),
        ),
    ];
    let staged = stage_all(generated_directory, &specifications)?;
    let result = commit_staged(generated_directory, &staged);
    if result.is_err() {
        for path in &staged {
            let _ = fs::remove_file(path);
        }
    }
    drop(lock);
    result
}

/// Atomically removes the authoritative generation from service while retaining it for diagnosis.
///
/// Call this immediately after any Flow source is successfully saved. A Runner looking only for
/// `generation.json` will then reject the project until a new generation is committed.
///
/// # Errors
///
/// Returns an error when another generation transaction is active or the atomic rename fails.
pub fn mark_generation_stale(generated_directory: &Path) -> Result<bool, CommitError> {
    fs::create_dir_all(generated_directory)
        .map_err(|error| io_error("create generated directory", generated_directory, &error))?;
    let lock = CommitLock::acquire(generated_directory)?;
    let current = generated_directory.join("generation.json");
    if !current.exists() {
        drop(lock);
        return Ok(false);
    }
    let stale = generated_directory.join("generation.stale.json");
    replace(&current, &stale)?;
    sync_directory(generated_directory)?;
    drop(lock);
    Ok(true)
}

fn stage_all(
    directory: &Path,
    specifications: &[(String, &[u8]); 3],
) -> Result<[PathBuf; 3], CommitError> {
    let mut paths = Vec::with_capacity(specifications.len());
    for (name, content) in specifications {
        match stage_file(directory, name, content) {
            Ok(path) => paths.push(path),
            Err(error) => {
                for path in paths {
                    let _ = fs::remove_file(path);
                }
                return Err(error);
            }
        }
    }
    paths
        .try_into()
        .map_err(|_| CommitError::InvalidBundle("internal staged file count mismatch".into()))
}

fn validate_bundle(bundle: &GenerationBundle) -> Result<(), CommitError> {
    let record: GenerationRecord = serde_json::from_slice(&bundle.generation_json)
        .map_err(|error| CommitError::InvalidBundle(error.to_string()))?;
    if record != bundle.record
        || record.lua_digest != content_digest(&bundle.main_lua)
        || record.source_map_digest != content_digest(&bundle.source_map_json)
    {
        return Err(CommitError::InvalidBundle(
            "generation record digests do not match payloads".into(),
        ));
    }
    let source_map: SourceMap = serde_json::from_slice(&bundle.source_map_json)
        .map_err(|error| CommitError::InvalidBundle(error.to_string()))?;
    let expected_lua_header = format!(
        "-- @generated by flow-compiler; do not edit.\n-- generationId: {}\n",
        record.generation_id
    );
    if source_map.generation_id != record.generation_id
        || !bundle.main_lua.starts_with(expected_lua_header.as_bytes())
    {
        return Err(CommitError::InvalidBundle(
            "payload generationId does not match record".into(),
        ));
    }
    Ok(())
}

fn stage_file(directory: &Path, name: &str, content: &[u8]) -> Result<PathBuf, CommitError> {
    let path = directory.join(name);
    if path.exists() {
        fs::remove_file(&path)
            .map_err(|error| io_error("remove abandoned staged file", &path, &error))?;
    }
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&path)
        .map_err(|error| io_error("create staged file", &path, &error))?;
    file.write_all(content)
        .map_err(|error| io_error("write staged file", &path, &error))?;
    file.sync_all()
        .map_err(|error| io_error("sync staged file", &path, &error))?;
    Ok(path)
}

fn commit_staged(directory: &Path, staged: &[PathBuf; 3]) -> Result<(), CommitError> {
    replace(&staged[0], &directory.join("main.lua"))?;
    replace(&staged[1], &directory.join("source-map.json"))?;
    replace(&staged[2], &directory.join("generation.json"))?;
    sync_directory(directory)
}

fn replace(source: &Path, destination: &Path) -> Result<(), CommitError> {
    fs::rename(source, destination)
        .map_err(|error| io_error("atomically replace generated file", destination, &error))
}

#[cfg(unix)]
fn sync_directory(directory: &Path) -> Result<(), CommitError> {
    File::open(directory)
        .and_then(|file| file.sync_all())
        .map_err(|error| io_error("sync generated directory", directory, &error))
}

#[cfg(not(unix))]
fn sync_directory(directory: &Path) -> Result<(), CommitError> {
    fs::metadata(directory)
        .map(|_| ())
        .map_err(|error| io_error("verify generated directory", directory, &error))
}

struct CommitLock {
    _file: File,
}

impl CommitLock {
    fn acquire(directory: &Path) -> Result<Self, CommitError> {
        let path = directory.join(LOCK_FILE);
        let mut file = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(false)
            .open(&path)
            .map_err(|error| io_error("open generation lock", &path, &error))?;
        match fs4::FileExt::try_lock(&file) {
            Ok(()) => {}
            Err(TryLockError::WouldBlock) => return Err(CommitError::Busy),
            Err(TryLockError::Error(error)) => {
                return Err(io_error("acquire generation lock", &path, &error));
            }
        }
        file.set_len(0)
            .map_err(|error| io_error("reset generation lock", &path, &error))?;
        writeln!(file, "pid={}", std::process::id())
            .map_err(|error| io_error("write generation lock", &path, &error))?;
        file.sync_all()
            .map_err(|error| io_error("sync generation lock", &path, &error))?;
        Ok(Self { _file: file })
    }
}

fn io_error(operation: &'static str, path: &Path, error: &std::io::Error) -> CommitError {
    CommitError::Io {
        operation,
        path: path.to_owned(),
        message: error.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::{commit_generation, mark_generation_stale, CommitError, LOCK_FILE};
    use crate::digest::content_digest;
    use crate::model::{GenerationBundle, GenerationRecord, SourceMap};
    use std::fs;
    use std::fs::OpenOptions;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT_DIRECTORY: AtomicU64 = AtomicU64::new(1);

    fn test_directory() -> PathBuf {
        std::env::temp_dir().join(format!(
            "autoscript-flow-compiler-{}-{}",
            std::process::id(),
            NEXT_DIRECTORY.fetch_add(1, Ordering::Relaxed)
        ))
    }

    fn bundle() -> GenerationBundle {
        let generation_id = "gen-0123456789abcdef0123456789abcdef".to_string();
        let main_lua = format!(
            "-- @generated by flow-compiler; do not edit.\n-- generationId: {generation_id}\nreturn function() end\n"
        )
        .into_bytes();
        let mut source_map_json = serde_json::to_vec_pretty(&SourceMap {
            schema_version: 1,
            generation_id: generation_id.clone(),
            entries: Vec::new(),
        })
        .expect("source map");
        source_map_json.push(b'\n');
        let record = GenerationRecord {
            generation_id,
            flow_digest: "0".repeat(64),
            lua_digest: content_digest(&main_lua),
            source_map_digest: content_digest(&source_map_json),
            generator_version: "0.1.0".into(),
            runtime_api: "1.0".into(),
        };
        let mut generation_json = serde_json::to_vec_pretty(&record).expect("record");
        generation_json.push(b'\n');
        GenerationBundle {
            main_lua,
            source_map_json,
            generation_json,
            record,
        }
    }

    #[test]
    fn transaction_commits_payloads_and_record() {
        let directory = test_directory();
        let bundle = bundle();
        commit_generation(&directory, &bundle).expect("first commit");
        assert_eq!(
            fs::read(directory.join("main.lua")).expect("Lua"),
            bundle.main_lua
        );
        assert_eq!(
            fs::read(directory.join("source-map.json")).expect("source map"),
            bundle.source_map_json
        );
        assert_eq!(
            fs::read(directory.join("generation.json")).expect("record"),
            bundle.generation_json
        );
        commit_generation(&directory, &bundle).expect("replacement commit");
        fs::remove_dir_all(directory).expect("clean test directory");
    }

    #[test]
    fn concurrent_writer_is_rejected() {
        let directory = test_directory();
        fs::create_dir_all(&directory).expect("test directory");
        let held = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(false)
            .open(directory.join(LOCK_FILE))
            .expect("lock fixture");
        fs4::FileExt::try_lock(&held).expect("hold operating-system lock");
        assert_eq!(
            commit_generation(&directory, &bundle()),
            Err(CommitError::Busy)
        );
        drop(held);
        fs::remove_dir_all(directory).expect("clean test directory");
    }

    #[test]
    fn saved_flow_can_fail_closed_the_current_generation() {
        let directory = test_directory();
        commit_generation(&directory, &bundle()).expect("commit fixture");
        assert_eq!(mark_generation_stale(&directory), Ok(true));
        assert!(!directory.join("generation.json").exists());
        assert!(directory.join("generation.stale.json").exists());
        assert_eq!(mark_generation_stale(&directory), Ok(false));
        fs::remove_dir_all(directory).expect("clean test directory");
    }
}
