package com.autoscript.runner

import android.content.Context
import com.autoscript.runtime.api.RuntimeProtocol
import com.autoscript.runtime.client.RuntimeProjectResource
import com.autoscript.runtime.client.RuntimeProjectResourceKind
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileOutputStream
import java.nio.ByteBuffer
import java.security.MessageDigest
import org.json.JSONArray
import org.json.JSONObject

internal data class EmbeddedRelease(
    val releaseId: String,
    val projectId: String,
    val displayName: String,
    val versionName: String,
    val runtimeApi: String,
    val sourceMode: String,
    val capabilities: List<String>,
    val luaSource: ByteArray,
    val resources: List<RuntimeProjectResource>,
    val designWidth: Int,
    val designHeight: Int,
    val scaleMode: Int,
    val runnerUi: RunnerUiDefinition?,
    val sourceMap: RunnerSourceMap?,
)

internal data class RunnerUiDefinition(
    val description: String?,
    val fields: List<RunnerUiFieldDefinition>,
    val script: com.autoscript.script.ui.ScriptUiDefinition? = null,
    val rawJson: com.google.gson.JsonObject? = null,
)

internal data class RunnerUiFieldDefinition(
    val id: String,
    val label: String,
    val kind: RunnerUiFieldKind,
    val required: Boolean,
    val initialValue: RunnerUiValue,
    val minimum: Long?,
    val maximum: Long?,
    val options: List<String>,
)

internal enum class RunnerUiFieldKind { TEXT, INTEGER, BOOLEAN, CHOICE }

internal sealed interface RunnerUiValue {
    data class Text(val value: String) : RunnerUiValue
    data class Integer(val value: Long) : RunnerUiValue
    data class BooleanValue(val value: Boolean) : RunnerUiValue
}

internal data class RunnerSourceMap(
    val generationId: String,
    val entries: List<RunnerSourceMapEntry>,
)

internal data class RunnerSourceMapEntry(
    val flowId: String,
    val nodeId: String,
    val luaStartLine: Int,
    val luaEndLine: Int,
)

internal object EmbeddedReleaseLoader {
    fun load(
        context: Context,
        expectedApplicationId: String,
        expectedVersionCode: Int,
        expectedVersionName: String,
    ): EmbeddedRelease? {
        val rootEntries = context.assets.list(RELEASE_ASSET_ROOT).orEmpty()
        if (RELEASE_MANIFEST_NAME !in rootEntries) return null
        val manifestBytes = readAssetBounded(context, RELEASE_MANIFEST_PATH, MAX_MANIFEST_BYTES)
        val manifest = parseManifest(manifestBytes)
        require(manifest.applicationId == expectedApplicationId) {
            "发布包 applicationId 与 APK 不一致"
        }
        require(manifest.versionCode == expectedVersionCode) { "发布包 versionCode 与 APK 不一致" }
        require(manifest.versionName == expectedVersionName) { "发布包 versionName 与 APK 不一致" }
        require(calculateReleaseId(manifest) == manifest.releaseId) { "发布包元数据摘要不匹配" }

        val lua = readAssetBounded(context, assetPath(manifest.lua.path), MAX_LUA_BYTES)
        require(lua.size.toLong() == manifest.lua.size && sha256(lua) == manifest.lua.sha256) {
            "发布包 Lua 摘要不匹配"
        }
        var totalBytes = lua.size.toLong()
        val sourceMap = manifest.sourceMap?.let { artifact ->
            val bytes = readAssetBounded(
                context,
                assetPath(artifact.path),
                MAX_SOURCE_MAP_BYTES,
            )
            require(bytes.size.toLong() == artifact.size && sha256(bytes) == artifact.sha256) {
                "发布包 source map 摘要不匹配"
            }
            totalBytes = Math.addExact(totalBytes, bytes.size.toLong())
            parseSourceMap(bytes).also { parsed ->
                val header = (
                    "-- @generated by flow-compiler; do not edit.\n" +
                        "-- generationId: ${parsed.generationId}\n"
                    ).toByteArray(Charsets.UTF_8)
                require(lua.size >= header.size && lua.copyOfRange(0, header.size).contentEquals(header)) {
                    "发布包 Lua 与 source map 生成代次不一致"
                }
            }
        }
        val materializedRoot = File(context.filesDir, "embedded-releases/${manifest.releaseId}")
        require(materializedRoot.mkdirs() || materializedRoot.isDirectory) { "无法创建内置资源目录" }
        val canonicalRoot = materializedRoot.canonicalFile
        val runtimeResources = manifest.resources.map { resource ->
            val maximum = when (resource.kind) {
                "image" -> MAX_IMAGE_BYTES
                "glyphDictionary" -> MAX_DICTIONARY_BYTES
                else -> error("发布包含未知资源类型")
            }
            val bytes = readAssetBounded(context, assetPath(resource.bundlePath), maximum)
            require(bytes.size.toLong() == resource.size && sha256(bytes) == resource.sha256) {
                "发布资源摘要不匹配：${resource.logicalPath}"
            }
            totalBytes = Math.addExact(totalBytes, bytes.size.toLong())
            require(totalBytes <= MAX_RELEASE_BYTES) { "发布包载荷超过 512 MiB" }
            val target = File(canonicalRoot, resource.logicalPath).canonicalFile
            require(target.path.startsWith(canonicalRoot.path + File.separator) && target != canonicalRoot) {
                "发布资源路径越界"
            }
            writeVerifiedResource(target, bytes, resource.sha256)
            RuntimeProjectResource(
                kind = if (resource.kind == "image") {
                    RuntimeProjectResourceKind.IMAGE
                } else {
                    RuntimeProjectResourceKind.GLYPH_DICTIONARY
                },
                path = resource.logicalPath,
                file = target,
            )
        }
        return EmbeddedRelease(
            releaseId = manifest.releaseId,
            projectId = manifest.projectId,
            displayName = manifest.displayName,
            versionName = manifest.versionName,
            runtimeApi = manifest.runtimeApi,
            sourceMode = manifest.sourceMode,
            capabilities = manifest.capabilities,
            luaSource = lua,
            resources = runtimeResources,
            designWidth = manifest.design.width,
            designHeight = manifest.design.height,
            scaleMode = when (manifest.design.scaleMode) {
                "letterbox" -> RuntimeProtocol.SCALE_LETTERBOX
                "crop" -> RuntimeProtocol.SCALE_CROP
                "stretch" -> RuntimeProtocol.SCALE_STRETCH
                else -> error("发布包缩放模式无效")
            },
            runnerUi = manifest.runnerUi,
            sourceMap = sourceMap,
        )
    }

    private fun parseManifest(bytes: ByteArray): ParsedRelease {
        val root = JSONObject(bytes.toString(Charsets.UTF_8)).requireKeys(
            "formatVersion", "releaseId", "projectId", "displayName", "applicationId",
            "versionCode", "versionName", "runtimeApi", "sourceMode", "design", "lua", "resources",
            "capabilities", "runnerUi", "sourceMap",
        )
        require(root.requiredInt("formatVersion") == RELEASE_FORMAT_VERSION) { "不支持的发布包版本" }
        val designObject = root.getJSONObject("design").requireKeys(
            "width", "height", "scaleMode", "orientationPolicy",
        )
        val design = ParsedDesign(
            width = designObject.requiredInt("width").also { require(it in 1..32_768) },
            height = designObject.requiredInt("height").also { require(it in 1..32_768) },
            scaleMode = designObject.requiredString("scaleMode").also {
                require(it in setOf("letterbox", "crop", "stretch"))
            },
            orientationPolicy = designObject.requiredString("orientationPolicy").also {
                require(it in setOf("follow", "portrait", "landscape"))
            },
        )
        val lua = parseArtifact(root.getJSONObject("lua"))
        require(lua.path == "payload/main.lua" && lua.size in 1..MAX_LUA_BYTES.toLong()) {
            "发布包 Lua 声明无效"
        }
        val sourceMap = root.nullableObject("sourceMap")?.let(::parseArtifact)
        require(
            (root.requiredString("sourceMode") == "visual" && sourceMap != null &&
                sourceMap.path == "payload/source-map.json" &&
                sourceMap.size in 1..MAX_SOURCE_MAP_BYTES.toLong()) ||
                (root.requiredString("sourceMode") == "lua" && sourceMap == null),
        ) { "发布 source map 与源码类型不匹配" }
        val runnerUi = root.nullableObject("runnerUi")?.let(::parseRunnerUi)
        val resourceArray = root.getJSONArray("resources")
        require(resourceArray.length() <= MAX_RESOURCES) { "发布资源数量超过 256" }
        val resources = buildList {
            for (index in 0 until resourceArray.length()) {
                val value = resourceArray.getJSONObject(index).requireKeys(
                    "kind", "logicalPath", "bundlePath", "sha256", "size",
                )
                val kind = value.requiredString("kind")
                require(kind in setOf("image", "glyphDictionary")) { "未知发布资源类型" }
                val logicalPath = value.requiredString("logicalPath")
                require(validResourcePath(kind, logicalPath)) { "发布资源路径无效" }
                val bundlePath = value.requiredString("bundlePath")
                require(bundlePath == "payload/$logicalPath") { "发布资源映射无效" }
                val size = value.requiredLong("size")
                val maximum = if (kind == "image") MAX_IMAGE_BYTES else MAX_DICTIONARY_BYTES
                require(size in 1..maximum.toLong()) { "发布资源大小无效" }
                add(
                    ParsedResource(
                        kind = kind,
                        logicalPath = logicalPath,
                        bundlePath = bundlePath,
                        sha256 = value.requiredSha256("sha256"),
                        size = size,
                    ),
                )
            }
        }
        require(resources.zipWithNext().all { (left, right) -> left.logicalPath < right.logicalPath }) {
            "发布资源必须按路径严格排序且不能重复"
        }
        val projectId = root.requiredString("projectId")
        val displayName = root.requiredString("displayName")
        val applicationId = root.requiredString("applicationId")
        val versionName = root.requiredString("versionName")
        val runtimeApi = root.requiredString("runtimeApi")
        val sourceMode = root.requiredString("sourceMode")
        val capabilityArray = root.getJSONArray("capabilities")
        require(capabilityArray.length() <= MAX_CAPABILITIES) { "发布能力数量超过64" }
        val capabilities = buildList {
            for (index in 0 until capabilityArray.length()) {
                val capability = capabilityArray.get(index)
                require(capability is String) { "发布能力必须是字符串" }
                require(capability.length <= MAX_CAPABILITY_LENGTH && CAPABILITY.matches(capability)) {
                    "发布能力格式无效"
                }
                add(capability)
            }
        }
        require(capabilities.zipWithNext().all { (left, right) -> left < right }) {
            "发布能力必须严格排序且不能重复"
        }
        require(PROJECT_ID.matches(projectId)) { "发布项目 ID 无效" }
        require(displayName.isNotBlank() && displayName.length <= 128 && displayName.none(Char::isISOControl)) {
            "发布项目名无效"
        }
        require(APPLICATION_ID.matches(applicationId)) { "发布 applicationId 无效" }
        require(versionName.length in 1..64 && versionName.none(Char::isISOControl)) { "发布版本名无效" }
        require(RUNTIME_API.matches(runtimeApi)) { "发布 Runtime API 无效" }
        require(runtimeApiCompatible(runtimeApi, SUPPORTED_RUNTIME_API)) {
            "发布 Runtime API 与当前 Runner 不兼容"
        }
        require(sourceMode in setOf("lua", "visual")) { "发布源码模式无效" }
        return ParsedRelease(
            releaseId = root.requiredSha256("releaseId"),
            projectId = projectId,
            displayName = displayName,
            applicationId = applicationId,
            versionCode = root.requiredInt("versionCode").also { require(it in 1..2_100_000_000) },
            versionName = versionName,
            runtimeApi = runtimeApi,
            sourceMode = sourceMode,
            capabilities = capabilities,
            runnerUi = runnerUi,
            design = design,
            lua = lua,
            sourceMap = sourceMap,
            resources = resources,
        )
    }

    private fun parseArtifact(value: JSONObject): ParsedArtifact {
        value.requireKeys("path", "sha256", "size")
        return ParsedArtifact(
            path = value.requiredString("path"),
            sha256 = value.requiredSha256("sha256"),
            size = value.requiredLong("size"),
        )
    }

    private fun parseRunnerUi(value: JSONObject): RunnerUiDefinition {
        if (value.has("version")) {
            val script = com.autoscript.script.ui.ScriptUiDefinition.parse(value.toString())
            return RunnerUiDefinition(script.description, script.fields.map { f ->
                val kind = RunnerUiFieldKind.valueOf(f.kind.uppercase())
                val initial = when (kind) { RunnerUiFieldKind.INTEGER -> RunnerUiValue.Integer(f.initialValue.toLong()); RunnerUiFieldKind.BOOLEAN -> RunnerUiValue.BooleanValue(f.initialValue.toBooleanStrict()); else -> RunnerUiValue.Text(f.initialValue) }
                RunnerUiFieldDefinition(f.id, f.label, kind, f.required, initial, f.minimum, f.maximum, f.options)
            }, script, com.google.gson.JsonParser.parseString(value.toString()).asJsonObject)
        }
        value.requireKeys("description", "fields")
        val description = if (value.isNull("description")) null else value.requiredText("description")
        require(
            description == null ||
                (description.codePointLength() <= 512 && description.none(Char::isISOControl)),
        ) { "Runner配置说明无效" }
        val array = value.getJSONArray("fields")
        require(array.length() in 1..MAX_RUNNER_UI_FIELDS) { "Runner配置字段数量无效" }
        val ids = mutableSetOf<String>()
        val fields = buildList {
            for (index in 0 until array.length()) {
                val field = array.getJSONObject(index).requireKeys(
                    "id", "label", "kind", "required", "initialValue", "minimum", "maximum", "options",
                )
                val id = field.requiredString("id")
                val label = field.requiredString("label")
                val kind = when (field.requiredString("kind")) {
                    "text" -> RunnerUiFieldKind.TEXT
                    "integer" -> RunnerUiFieldKind.INTEGER
                    "boolean" -> RunnerUiFieldKind.BOOLEAN
                    "choice" -> RunnerUiFieldKind.CHOICE
                    else -> error("Runner配置字段类型无效")
                }
                require(FIELD_ID.matches(id) && ids.add(id)) { "Runner配置字段ID无效或重复" }
                require(label.codePointLength() <= 64 && label.none(Char::isISOControl)) {
                    "Runner配置字段标题无效"
                }
                val required = field.requiredBoolean("required")
                val minimum = field.nullableLong("minimum")
                val maximum = field.nullableLong("maximum")
                val optionsArray = field.getJSONArray("options")
                val options = buildList {
                    for (optionIndex in 0 until optionsArray.length()) {
                        val option = optionsArray.get(optionIndex)
                        require(
                            option is String && option.codePointLength() in 1..64 &&
                                option.none(Char::isISOControl),
                        ) { "Runner配置选项无效" }
                        add(option)
                    }
                }
                require(options.distinct().size == options.size && options.size <= 32) {
                    "Runner配置选项重复或过多"
                }
                val initial = when (kind) {
                    RunnerUiFieldKind.TEXT -> RunnerUiValue.Text(
                        field.requiredText("initialValue").also {
                            require(it.codePointLength() <= 256 && '\u0000' !in it)
                        },
                    )
                    RunnerUiFieldKind.INTEGER -> RunnerUiValue.Integer(
                        field.requiredLong("initialValue"),
                    )
                    RunnerUiFieldKind.BOOLEAN -> RunnerUiValue.BooleanValue(
                        field.requiredBoolean("initialValue"),
                    )
                    RunnerUiFieldKind.CHOICE -> RunnerUiValue.Text(
                        field.requiredString("initialValue"),
                    )
                }
                when (kind) {
                    RunnerUiFieldKind.TEXT, RunnerUiFieldKind.BOOLEAN -> require(
                        minimum == null && maximum == null && options.isEmpty(),
                    ) { "Runner配置字段包含无关约束" }
                    RunnerUiFieldKind.INTEGER -> {
                        val number = (initial as RunnerUiValue.Integer).value
                        val low = minimum ?: -1_000_000_000L
                        val high = maximum ?: 1_000_000_000L
                        require(low <= number && number <= high && options.isEmpty()) {
                            "Runner配置整数默认值越界"
                        }
                    }
                    RunnerUiFieldKind.CHOICE -> require(
                        minimum == null && maximum == null && options.isNotEmpty() &&
                            (initial as RunnerUiValue.Text).value in options,
                    ) { "Runner配置选项默认值无效" }
                }
                add(
                    RunnerUiFieldDefinition(
                        id, label, kind, required, initial, minimum, maximum, options,
                    ),
                )
            }
        }
        return RunnerUiDefinition(description, fields)
    }

    private fun parseSourceMap(bytes: ByteArray): RunnerSourceMap {
        val root = JSONObject(bytes.toString(Charsets.UTF_8)).requireKeys(
            "schemaVersion", "generationId", "entries",
        )
        require(root.requiredInt("schemaVersion") == 1) { "不支持的 source map 版本" }
        val generationId = root.requiredString("generationId").also {
            require(GENERATION_ID.matches(it)) { "source map generationId无效" }
        }
        val array = root.getJSONArray("entries")
        require(array.length() <= MAX_SOURCE_MAP_ENTRIES) { "source map 条目过多" }
        val entries = buildList {
            for (index in 0 until array.length()) {
                val entry = array.getJSONObject(index).requireKeys(
                    "flowId", "nodeId", "luaStartLine", "luaEndLine",
                )
                val start = entry.requiredInt("luaStartLine")
                val end = entry.requiredInt("luaEndLine")
                require(start in 1..end) { "source map 行范围无效" }
                add(
                    RunnerSourceMapEntry(
                        flowId = entry.requiredString("flowId").also {
                            require(it.codePointLength() <= 128 && it.none(Char::isISOControl))
                        },
                        nodeId = entry.requiredString("nodeId").also {
                            require(it.codePointLength() <= 128 && it.none(Char::isISOControl))
                        },
                        luaStartLine = start,
                        luaEndLine = end,
                    ),
                )
            }
        }
        return RunnerSourceMap(generationId, entries)
    }

    private fun calculateReleaseId(release: ParsedRelease): String {
        val digest = MessageDigest.getInstance("SHA-256")
        listOf(
            RELEASE_FORMAT_VERSION.toString(),
            release.projectId,
            release.displayName,
            release.applicationId,
            release.versionCode.toString(),
            release.versionName,
            release.runtimeApi,
            release.sourceMode,
            release.capabilities.size.toString(),
            release.design.width.toString(),
            release.design.height.toString(),
            release.design.scaleMode,
            release.design.orientationPolicy,
            release.lua.path,
            release.lua.sha256,
            release.lua.size.toString(),
            release.sourceMap.isPresent.toString(),
            release.resources.size.toString(),
            release.runnerUi.isPresent.toString(),
        ).forEach { digestField(digest, it) }
        release.capabilities.forEach { digestField(digest, it) }
        release.sourceMap?.let { artifact ->
            listOf(artifact.path, artifact.sha256, artifact.size.toString()).forEach {
                digestField(digest, it)
            }
        }
        release.runnerUi?.let { ui ->
            digestField(digest, ui.description.isPresent.toString())
            ui.description?.let { digestField(digest, it) }
            digestField(digest, ui.fields.size.toString())
            ui.fields.forEach { field ->
                listOf(
                    field.id,
                    field.label,
                    field.kind.name.lowercase(),
                    field.required.toString(),
                    field.initialValue.digestValue(),
                    field.minimum.isPresent.toString(),
                ).forEach { digestField(digest, it) }
                field.minimum?.let { digestField(digest, it.toString()) }
                digestField(digest, field.maximum.isPresent.toString())
                field.maximum?.let { digestField(digest, it.toString()) }
                digestField(digest, field.options.size.toString())
                field.options.forEach { digestField(digest, it) }
                ui.script?.takeIf { it.version == 2 }?.let { script ->
                    val raw = (ui.rawJson ?: script.toJson()).getAsJsonArray("fields").single { it.asJsonObject.get("id").asString == field.id }.asJsonObject.get("ui")
                    digestField(digest, com.autoscript.script.ui.canonicalUiJson(raw))
                }
            }
            ui.script?.takeIf { it.version == 2 }?.let { script ->
                digestField(digest, "2")
                digestField(digest, com.autoscript.script.ui.canonicalUiJson((ui.rawJson ?: script.toJson()).get("pages")))
            }
        }
        release.resources.forEach { resource ->
            listOf(
                resource.kind,
                resource.logicalPath,
                resource.bundlePath,
                resource.sha256,
                resource.size.toString(),
            ).forEach { digestField(digest, it) }
        }
        return digest.digest().toHex()
    }

    private val Any?.isPresent: Boolean get() = this != null

    private fun RunnerUiValue.digestValue(): String = when (this) {
        is RunnerUiValue.Text -> value
        is RunnerUiValue.Integer -> value.toString()
        is RunnerUiValue.BooleanValue -> value.toString()
    }

    private fun digestField(digest: MessageDigest, value: String) {
        val bytes = value.toByteArray(Charsets.UTF_8)
        digest.update(ByteBuffer.allocate(Long.SIZE_BYTES).putLong(bytes.size.toLong()).array())
        digest.update(bytes)
    }

    private fun readAssetBounded(context: Context, path: String, maximum: Int): ByteArray =
        context.assets.open(path).use { input ->
            val output = ByteArrayOutputStream(minOf(maximum, DEFAULT_BUFFER_SIZE))
            val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
            var total = 0
            while (true) {
                val count = input.read(buffer)
                if (count < 0) break
                if (count == 0) continue
                total = Math.addExact(total, count)
                require(total <= maximum) { "发布文件超过大小上限：$path" }
                output.write(buffer, 0, count)
            }
            require(total > 0) { "发布文件为空：$path" }
            output.toByteArray()
        }

    private fun writeVerifiedResource(target: File, bytes: ByteArray, expectedDigest: String) {
        if (target.isFile && target.length() == bytes.size.toLong() && sha256(target.readBytes()) == expectedDigest) {
            return
        }
        target.parentFile?.let { require(it.mkdirs() || it.isDirectory) { "无法创建发布资源目录" } }
        val temporary = File(target.parentFile, ".${target.name}.tmp")
        try {
            FileOutputStream(temporary).use { output ->
                output.write(bytes)
                output.flush()
                output.fd.sync()
            }
            if (target.exists()) require(target.delete()) { "无法替换旧发布资源" }
            require(temporary.renameTo(target)) { "无法提交发布资源" }
        } finally {
            temporary.delete()
        }
    }

    private fun validResourcePath(kind: String, path: String): Boolean =
        path.length in 1..256 && '\\' !in path && '\u0000' !in path &&
            path.split('/').all { it.isNotEmpty() && it != "." && it != ".." } &&
            if (kind == "image") {
                path.startsWith("assets/images/")
            } else {
                path.startsWith("dictionaries/") && path.endsWith(".asglyph")
            }

    private fun assetPath(bundlePath: String): String = "$RELEASE_ASSET_ROOT/$bundlePath"

    private fun runtimeApiCompatible(required: String, supported: String): Boolean {
        val requiredParts = required.split('.').mapNotNull(String::toIntOrNull)
        val supportedParts = supported.split('.').mapNotNull(String::toIntOrNull)
        return requiredParts.size == 2 && supportedParts.size == 2 &&
            requiredParts[0] == supportedParts[0] && requiredParts[1] <= supportedParts[1]
    }

    private fun sha256(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(bytes).toHex()

    private fun ByteArray.toHex(): String = joinToString("") {
        (it.toInt() and 0xff).toString(16).padStart(2, '0')
    }

    private fun JSONObject.requireKeys(vararg expected: String): JSONObject {
        require(keys().asSequence().toSet() == expected.toSet()) { "发布清单字段不完整或含未知字段" }
        return this
    }

    private fun JSONObject.requiredString(name: String): String =
        get(name).let { value -> require(value is String && value.isNotEmpty()) { "$name 必须是非空字符串" }; value }

    private fun JSONObject.requiredText(name: String): String =
        get(name).let { value -> require(value is String) { "$name 必须是字符串" }; value }

    private fun JSONObject.requiredSha256(name: String): String = requiredString(name).also {
        require(SHA256.matches(it)) { "$name 不是规范 SHA-256" }
    }

    private fun JSONObject.requiredInt(name: String): Int {
        val value = get(name)
        require(value is Int || value is Long) { "$name 必须是整数" }
        return (value as Number).toLong().also { require(it in Int.MIN_VALUE..Int.MAX_VALUE) }.toInt()
    }

    private fun JSONObject.requiredLong(name: String): Long {
        val value = get(name)
        require(value is Int || value is Long) { "$name 必须是整数" }
        return (value as Number).toLong()
    }

    private fun JSONObject.requiredBoolean(name: String): Boolean {
        val value = get(name)
        require(value is Boolean) { "$name 必须是布尔值" }
        return value
    }

    private fun JSONObject.nullableLong(name: String): Long? =
        if (isNull(name)) null else requiredLong(name)

    private fun JSONObject.nullableObject(name: String): JSONObject? =
        if (isNull(name)) null else getJSONObject(name)

    private data class ParsedRelease(
        val releaseId: String,
        val projectId: String,
        val displayName: String,
        val applicationId: String,
        val versionCode: Int,
        val versionName: String,
        val runtimeApi: String,
        val sourceMode: String,
        val capabilities: List<String>,
        val runnerUi: RunnerUiDefinition?,
        val design: ParsedDesign,
        val lua: ParsedArtifact,
        val sourceMap: ParsedArtifact?,
        val resources: List<ParsedResource>,
    )

    private data class ParsedDesign(
        val width: Int,
        val height: Int,
        val scaleMode: String,
        val orientationPolicy: String,
    )

    private data class ParsedArtifact(val path: String, val sha256: String, val size: Long)

    private data class ParsedResource(
        val kind: String,
        val logicalPath: String,
        val bundlePath: String,
        val sha256: String,
        val size: Long,
    )

    private const val RELEASE_FORMAT_VERSION = 3
    private const val RELEASE_ASSET_ROOT = "autoscript-release"
    private const val RELEASE_MANIFEST_NAME = "release.json"
    private const val RELEASE_MANIFEST_PATH = "$RELEASE_ASSET_ROOT/$RELEASE_MANIFEST_NAME"
    private const val MAX_MANIFEST_BYTES = 1024 * 1024
    private const val MAX_LUA_BYTES = 16 * 1024 * 1024
    private const val MAX_SOURCE_MAP_BYTES = 8 * 1024 * 1024
    private const val MAX_IMAGE_BYTES = 32 * 1024 * 1024
    private const val MAX_DICTIONARY_BYTES = 8 * 1024 * 1024
    private const val MAX_RELEASE_BYTES = 512L * 1024 * 1024
    private const val MAX_RESOURCES = 256
    private const val MAX_CAPABILITIES = 64
    private const val MAX_CAPABILITY_LENGTH = 128
    private const val MAX_RUNNER_UI_FIELDS = 32
    private const val MAX_SOURCE_MAP_ENTRIES = 100_000
    private const val SUPPORTED_RUNTIME_API = "1.7"
    private val PROJECT_ID = Regex("[A-Za-z0-9][A-Za-z0-9._-]{0,63}")
    private val APPLICATION_ID = Regex("[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+")
    private val RUNTIME_API = Regex("[0-9]+\\.[0-9]+")
    private val CAPABILITY = Regex("[a-z][a-z0-9]*(\\.[a-z][a-z0-9]*)+")
    private val FIELD_ID = Regex("[A-Za-z_][A-Za-z0-9_]{0,63}")
    private val GENERATION_ID = Regex("gen-[0-9a-f]{32}")
    private val SHA256 = Regex("[0-9a-f]{64}")
}

private fun String.codePointLength(): Int = codePointCount(0, length)
