-- @generated by flow-compiler; do not edit.
-- generationId: gen-dd98d01d178920c567fd8488cd784364
-- @autoscript project popup style
local __autoscript_toast_impl = Prompt.toast
Prompt.toast = function(message, styleJson) return __autoscript_toast_impl(message, styleJson or "{\"widthPx\":520,\"heightPx\":144,\"xPx\":-1,\"yPx\":-1,\"backgroundColor\":\"#B3000000\",\"textColor\":\"#FFFFFFFF\",\"fontPx\":32,\"cornerPx\":16,\"durationMs\":3000,\"textAlign\":\"center\"}") end
local __autoscript_debug_event = __autoscript_debug_event or function() end
local __flows = {}
local __recognition_ticks = {}
local function __recognition_visit(key, every) local tick = __recognition_ticks[key] or 0; __recognition_ticks[key] = (tick + 1) % every; return tick == 0 end
local function __checkpoint(flow, node, locals, globals, localTypes, globalTypes)
  if not __autoscript_debug_capture then return end
  __autoscript_debug_snapshot = {flowId=flow,nodeId=node,locals=locals,globals=globals,localTypes=localTypes,globalTypes=globalTypes}
  if __autoscript_debug_target_node then
    if flow ~= __autoscript_debug_target_flow or node ~= __autoscript_debug_target_node then return end
    __autoscript_debug_target_node = nil; __autoscript_debug_target_flow = nil; __autoscript_debug_step = true
    if __autoscript_debug_execute_target then __autoscript_debug_execute_target = nil; return end
  end
  if __autoscript_debug_step then coroutine.yield('__AUTOSCRIPT_DEBUG_CHECKPOINT_V1') end
end
local __globals = {}
local __global_types = {}
local function __default(kind) if kind == 'integer' or kind == 'number' then return 0 elseif kind == 'string' then return '' end end
local function __variable_check(name, kind, value)
  if value == nil or kind == nil then return end
  local valid = (kind == 'string' and type(value) == 'string') or (kind == 'boolean' and type(value) == 'boolean')
  if type(value) == 'number' and value == value and value ~= math.huge and value ~= -math.huge then valid = kind == 'number' or (kind == 'integer' and value % 1 == 0) or (kind == 'image' and value % 1 == 0 and value > 0) end
  if not valid then error('变量类型不匹配: ' .. name .. ' (' .. kind .. ')', 0) end
end
local function __channel_value(value)
  local kind = type(value)
  if kind ~= 'boolean' and kind ~= 'string' and kind ~= 'number' then error('调用/返回参数必须为非空标量', 0) end
  if kind == 'number' and (value ~= value or value == math.huge or value == -math.huge) then error('调用/返回参数必须为有限数值', 0) end
  return value
end
local function __compare(left, operator, right)
  if operator == "equals" then return left == right end
  if operator == "notEquals" then return left ~= right end
  local kind = type(left)
  if kind ~= type(right) or (kind ~= "number" and kind ~= "string") then return false end
  if operator == "lessThan" then return left < right end
  if operator == "lessOrEqual" then return left <= right end
  if operator == "greaterThan" then return left > right end
  if operator == "greaterOrEqual" then return left >= right end
  return false
end

__flows["child"] = function(__args)
  __args = __args or {}
  local __locals, __local_types = {}, {}
  for name, kind in pairs(__local_types) do __locals[name] = __default(kind) end
  local __vars = setmetatable({}, {
    __index = function(_, name) if __local_types[name] or not __global_types[name] then return __locals[name] end return __globals[name] end,
    __newindex = function(_, name, value) local kind = __local_types[name] or __global_types[name]; __variable_check(name, kind, value); if __local_types[name] or not __global_types[name] then __locals[name] = value else __globals[name] = value end end
  })
  local __call_args = {}
  local __last_return_values = {}
  local __return_values = {}
  local function __checked_return()
    return __return_values
  end
  __autoscript_debug_event("flowStart", "child", "", "")
  __checkpoint("child", "child-0", __locals, __globals, __local_types, __global_types)
  do end
  __autoscript_debug_event("flowReturn", "child", "", "")
  return __checked_return()
end

__flows["main"] = function(__args)
  __args = __args or {}
  local __locals, __local_types = {}, {}
  for name, kind in pairs(__local_types) do __locals[name] = __default(kind) end
  local __vars = setmetatable({}, {
    __index = function(_, name) if __local_types[name] or not __global_types[name] then return __locals[name] end return __globals[name] end,
    __newindex = function(_, name, value) local kind = __local_types[name] or __global_types[name]; __variable_check(name, kind, value); if __local_types[name] or not __global_types[name] then __locals[name] = value else __globals[name] = value end end
  })
  local __call_args = {}
  local __last_return_values = {}
  local __return_values = {}
  local function __checked_return()
    return __return_values
  end
  __autoscript_debug_event("flowStart", "main", "", "")
  __checkpoint("main", "main-0", __locals, __globals, __local_types, __global_types)
  do end
  __autoscript_debug_event("flowReturn", "main", "", "")
  return __checked_return()
end

return function(__entry_args)
  __recognition_ticks = {}
  __globals = {}
  for name, kind in pairs(__global_types) do __globals[name] = __default(kind) end
  __flows["main"](__entry_args or {})
  return nil
end
