---@meta
-- @generated by api-codegen; do not edit.

Math = Math or {}

---计算两个设计坐标点之间的欧氏距离。
---@param x1 number 起点X坐标。
---@param y1 number 起点Y坐标。
---@param x2 number 终点X坐标。
---@param y2 number 终点Y坐标。
---@return number value 非负距离。
function Math.distance(x1, y1, x2, y2) end

Log = Log or {}

---向当前 Runner 的有界调试日志写入一条文本。
---@param level integer 1=info，2=warn，3=error。
---@param message string 最多2048字节的 UTF-8 文本。
function Log.write(level, message) end

Prompt = Prompt or {}

---向脚本使用者显示一条运行中的提示信息。
---@param message string 最多2048字节的 UTF-8 提示文本。
function Prompt.show(message) end

---按项目提示样式显示一条短时弹出提示。
---@param message string 最多2048字节的 UTF-8 提示文本。
---@param styleJson string 可选的受限提示样式 JSON；缺省使用默认样式。
function Prompt.toast(message, styleJson) end

UI = UI or {}

---等待下一条界面事件；协程挂起，事件唤醒，最多30分钟无交互超时。
---@return string value 等待下一条界面事件；协程挂起，事件唤醒，最多30分钟无交互超时。
function UI.waitEvent() end

---读取控件字符串值。
---@param id string id
---@return string value 读取控件字符串值。
function UI.getValue(id) end

---设置控件值，不触发用户事件。
---@param id string id
---@param value string value
function UI.setValue(id, value) end

---白名单控件操作：text、visible、enabled、items、progress、page、show、hide、minimize。
---@param id string id
---@param operation string operation
---@param value string value
function UI.command(id, operation, value) end

System = System or {}

---读取当前Android显示区域的物理像素尺寸。
---@return Size value 包含width和height的尺寸值。
function System.getScreenSize() end

---读取当前任务运行所使用的单调时钟毫秒值。
---@return Integer value 自设备启动以来的单调毫秒数。
function System.elapsedRealtimeMillis() end

Task = Task or {}

---挂起当前Lua协程，期间不阻塞调度线程，并响应任务取消。
---@param milliseconds integer 非负等待毫秒数。
function Task.sleep(milliseconds) end

---在同一Lua VM启动子任务；父任务结束时自动取消，失败向父任务传播。
---@param callback function 无参数回调，只保存在VM内，宿主边界仅传不透明登记ID。
---@return integer value 子任务ID，仅创建者可取消。
function Task.spawn(callback) end

---优先取消自己创建的子任务，不能取消其他任务或父任务。
---@param task integer Task.spawn返回的ID。
---@return boolean value 是否找到可取消的子任务。
function Task.cancel(task) end

Timer = Timer or {}

---创建非重入周期回调；错过tick合并，回调失败终止所有者，父任务结束自动取消。
---@param milliseconds integer 10–60000毫秒。
---@param callback function VM内无参数回调，不能通过宿主边界。
---@return integer value 定时器ID，仅创建者可取消。
function Timer.every(milliseconds, callback) end

---取消自己的周期定时器及正在运行的回调。
---@param timer integer Timer.every返回的ID。
---@return boolean value 是否找到所属定时器。
function Timer.cancel(timer) end

Input = Input or {}

---在设计坐标中执行一次点击，并等待Root输入后端确认。
---@param x integer 设计坐标X。
---@param y integer 设计坐标Y。
function Input.tap(x, y) end

---在两个设计坐标之间执行有限时长滑动。
---@param x1 integer 起点X。
---@param y1 integer 起点Y。
---@param x2 integer 终点X。
---@param y2 integer 终点Y。
---@param durationMs integer 1至5000毫秒。
function Input.swipe(x1, y1, x2, y2, durationMs) end

---发送一个白名单校验后的Android键码。
---@param keyCode integer 非负Android KeyEvent键码。
function Input.keyEvent(keyCode) end

---在设计坐标按下单指触点；触点由当前任务持有，任务结束或超时自动释放。
---@param x integer 设计坐标X。
---@param y integer 设计坐标Y。
function Input.pointerDown(x, y) end

---移动当前任务持有的单指触点；未按下或非持有任务调用会失败。
---@param x integer 设计坐标X。
---@param y integer 设计坐标Y。
function Input.pointerMove(x, y) end

---释放当前任务持有的单指触点；其他任务不能代替持有者释放。
function Input.pointerUp() end

---按原始屏幕像素点击，不再进行设计坐标缩放。
---@param x integer 原始屏幕X像素。
---@param y integer 原始屏幕Y像素。
function Input.tapScreen(x, y) end

---按原始屏幕像素按住单触点，使用既有任务触点租约和弹起清理。
---@param x integer 原始屏幕X像素。
---@param y integer 原始屏幕Y像素。
function Input.pointerDownScreen(x, y) end

Screen = Screen or {}

---请求一帧屏幕图像，返回短生命周期采集编号。
---@return integer value 可传给Screen.cache的采集编号。
function Screen.capture() end

---把当前采集帧固定为任务拥有的不可变识图帧。
---@param captureId integer Screen.capture返回的采集编号。
---@return integer value 任务范围内有效的帧句柄。
function Screen.cache(captureId) end

---显式释放当前任务持有的一份帧租约。
---@param frame integer Screen.cache返回的帧句柄。
function Screen.release(frame) end

---加载已冻结到项目中的图片资源，并取得任务范围内有效的不可变模板帧。
---@param path string 以assets/images/开头的规范项目资源路径。
---@return integer value 可传给Screen.findImage并用Screen.release释放的模板帧句柄。
function Screen.loadImage(path) end

---从已有帧裁剪半开矩形，返回任务拥有的独立不可变图像句柄，需Screen.release释放。
---@param frame integer 源帧句柄。
---@param left integer 左边界。
---@param top integer 上边界。
---@param right integer 右边界，不包含。
---@param bottom integer 下边界，不包含。
---@return integer value 裁剪图像句柄；任务结束时自动清理。
function Screen.crop(frame, left, top, right, bottom) end

---在租用帧的半开ROI内按行优先查找颜色。
---@param frame integer 任务持有的帧句柄。
---@param rgb integer 0xRRGGBB颜色。
---@param tolerance integer 0至255的逐通道容差。
---@param left integer ROI左边界，包含。
---@param top integer ROI上边界，包含。
---@param right integer ROI右边界，不包含。
---@param bottom integer ROI下边界，不包含。
---@return Point value 首个匹配点；未找到时为nil。
function Screen.findColor(frame, rgb, tolerance, left, top, right, bottom) end

---使用不可变模板帧执行有界透明像素模板匹配。
---@param frame integer 待搜索帧句柄。
---@param template integer 模板帧句柄。
---@param tolerance integer 0至255的逐通道容差。
---@param similarityPermille integer 0至1000的最低相似度。
---@param left integer ROI左边界，包含。
---@param top integer ROI上边界，包含。
---@param right integer ROI右边界，不包含。
---@param bottom integer ROI下边界，不包含。
---@param direction integer API 1.7新增：0左上、1右上、2左下、3右下、4中心向外；省略为0。与旧版多点找色枚举独立。
---@return Point value 首个匹配模板的左上角；未找到时为nil。
function Screen.findImage(frame, template, tolerance, similarityPermille, left, top, right, bottom, direction) end

---读取任务所持不可变帧中的一个像素，返回0xRRGGBB。
---@param frame integer 任务持有的帧句柄。
---@param x integer 帧内横坐标。
---@param y integer 帧内纵坐标。
---@return integer value 0xRRGGBB颜色值。
function Screen.getColor(frame, x, y) end

---比较帧内一个像素与目标颜色是否落在逐通道容差内。
---@param frame integer 任务持有的帧句柄。
---@param x integer 帧内横坐标。
---@param y integer 帧内纵坐标。
---@param rgb integer 0xRRGGBB目标颜色。
---@param tolerance integer 0至255的逐通道容差。
---@return boolean value 是否匹配。
function Screen.compareColor(frame, x, y, rgb, tolerance) end

---在半开ROI内按行优先查找锚点色和最多64个有符号偏移采样点。
---@param frame integer 任务持有的帧句柄。
---@param anchorRgb integer 0xRRGGBB锚点颜色。
---@param anchorTolerance integer 锚点逐通道容差。
---@param samples MultiColorSample[] 附加采样点表；每项包含x、y、rgb、tolerance。
---@param left integer ROI左边界，包含。
---@param top integer ROI上边界，包含。
---@param right integer ROI右边界，不包含。
---@param bottom integer ROI下边界，不包含。
---@return Point value 首个匹配锚点；未找到时为nil。
function Screen.findMultiColor(frame, anchorRgb, anchorTolerance, samples, left, top, right, bottom) end

---统计半开ROI内的匹配颜色，达到limit后立即返回。
---@param frame integer 任务持有的帧句柄。
---@param rgb integer 0xRRGGBB目标颜色。
---@param tolerance integer 0至255的逐通道容差。
---@param left integer ROI左边界，包含。
---@param top integer ROI上边界，包含。
---@param right integer ROI右边界，不包含。
---@param bottom integer ROI下边界，不包含。
---@param limit integer 1至256的提前停止上限。
---@return integer value 匹配数量，最大为limit。
function Screen.countColor(frame, rgb, tolerance, left, top, right, bottom, limit) end

---按行优先返回半开ROI内最多limit个匹配颜色坐标。
---@param frame integer 任务持有的帧句柄。
---@param rgb integer 0xRRGGBB目标颜色。
---@param tolerance integer 0至255的逐通道容差。
---@param left integer ROI左边界，包含。
---@param top integer ROI上边界，包含。
---@param right integer ROI右边界，不包含。
---@param bottom integer ROI下边界，不包含。
---@param limit integer 1至256的返回数量上限。
---@return Point[] value 按行优先排序的坐标数组。
function Screen.findAllColor(frame, rgb, tolerance, left, top, right, bottom, limit) end

---按给定顺序匹配1–64个已声明图片，共享比较预算，返回第一个匹配的模板标识、坐标与得分。
---@param frame integer 缓存帧句柄。
---@param pathsJson string 已声明模板路径的JSON字符串数组，最多64项和16384字节。
---@param tolerance integer 通道容差0–255。
---@param similarityPermille integer 相似度0–1000。
---@param left integer 左边界。
---@param top integer 上边界。
---@param right integer 右边界，不包含。
---@param bottom integer 下边界，不包含。
---@param direction integer 0左上、1右上、2左下、3右下、4中心向外，默认0。
---@return TemplateMatch value x/y、path、scorePermille、width/height；没有匹配为nil。
function Screen.findImages(frame, pathsJson, tolerance, similarityPermille, left, top, right, bottom, direction) end

---OpenCV灰度归一化平方差找图，返回最高分位置；不支持缩放旋转，与像素算法得分不同。
---@param frame integer 缓存帧。
---@param template integer Screen.loadImage加载的声明图片帧。
---@param similarityPermille integer 最低灰度得分0–1000。
---@param left integer 左边界。
---@param top integer 上边界。
---@param right integer 右边界，不含。
---@param bottom integer 下边界，不含。
---@return GrayMatchResult value x/y和scorePermille；无匹配nil。
function Screen.findGray(frame, template, similarityPermille, left, top, right, bottom) end

Legacy = Legacy or {}

---按旧版严格字符串语法、宽高ROI、百分比阈值和指定方向执行多点找色。
---@param frame integer 任务持有的显式不可变帧句柄，替代旧版隐式全局屏幕。
---@param left integer 旧版ROI起点X。
---@param top integer 旧版ROI起点Y。
---@param width integer 旧版ROI宽度，大于0。
---@param height integer 旧版ROI高度，大于0。
---@param parameters string 锚点色与有符号相对点组成的严格旧版参数串。
---@param direction integer 搜索方向0至4，映射与旧版一致。
---@param minimumMatchPercent integer 0至100的最低匹配点百分比，使用向上取整。
---@return XunTuResult value 包含count、first和有序points的兼容寻图结果。
function Legacy.duoDianZhaoSe(frame, left, top, width, height, parameters, direction, minimumMatchPercent) end

---按旧版绝对坐标参数串和百分比向上取整规则执行多点比色。
---@param frame integer 任务持有的显式不可变帧句柄。
---@param parameters string 绝对坐标、颜色和逐通道容差组成的严格旧版参数串。
---@param minimumMatchPercent integer 0至100的最低匹配点百分比，使用向上取整。
---@return integer value 匹配返回1，不匹配返回0，保留旧版整数语义。
function Legacy.duoDianBiSe(frame, parameters, minimumMatchPercent) end

---统计旧版宽高ROI内命中任一严格颜色参数的像素总数。
---@param frame integer 任务持有的显式不可变帧句柄。
---@param left integer 旧版ROI起点X。
---@param top integer 旧版ROI起点Y。
---@param width integer 旧版ROI宽度，大于0。
---@param height integer 旧版ROI高度，大于0。
---@param parameters string 一个或多个颜色及逐通道容差组成的严格旧版参数串。
---@return integer value ROI内命中像素总数。
function Legacy.getRectColorNum(frame, left, top, width, height, parameters) end

---按旧版GetRGBColor语义将三个颜色通道组合成0xRRGGBB整数。
---@param red integer 0至255的红色通道。
---@param green integer 0至255的绿色通道。
---@param blue integer 0至255的蓝色通道。
---@return integer value 0xRRGGBB整数颜色。
function Legacy.getRgbColor(red, green, blue) end

---按帧数、持续时间和目标FPS采集有界连续帧；启动时预留最坏情况内存。
---@param maxFrames integer 1至120的最大帧数，仍受会话字节预算限制。
---@param durationMs integer 1至60000毫秒的最长持续时间。
---@param targetFps integer 1至120的目标采样帧率。
---@param allowPartial boolean 几何变化时是否允许返回已完成部分。
---@return CaptureSeriesResult value 包含帧句柄与实际时间戳、丢帧数和partial标记。
function Screen.captureSeries(maxFrames, durationMs, targetFps, allowPartial) end

Ocr = Ocr or {}

---加载已冻结到项目中的基础字库，并取得任务范围内有效的字库句柄。
---@param path string 以dictionaries/开头的规范项目资源路径。
---@return integer value 可传给Ocr.glyph并用Ocr.releaseDictionary释放的字库句柄。
function Ocr.loadDictionary(path) end

---释放当前任务持有的基础字库句柄。
---@param dictionary integer Ocr.loadDictionary返回的字库句柄。
function Ocr.releaseDictionary(dictionary) end

---在不可变帧的指定区域中二值化、分行分字，并使用基础字库逐字匹配。
---@param frame integer 待识别的缓存帧句柄。
---@param dictionary integer 基础字库句柄。
---@param foregroundRgb integer 0xRRGGBB格式的前景色。
---@param tolerance integer 0至255的逐通道颜色容差。
---@param similarityPermille integer 0至1000的最低字形相似度。
---@param left integer ROI左边界，包含。
---@param top integer ROI上边界，包含。
---@param right integer ROI右边界，不包含。
---@param bottom integer ROI下边界，不包含。
---@param spaceGapColumns integer 插入空格所需的最小连续空列数，0表示不插入。
---@return GlyphOcrResult value 包含text、coveragePermille和averageScorePermille的识别结果。
function Ocr.glyph(frame, dictionary, foregroundRgb, tolerance, similarityPermille, left, top, right, bottom, spaceGapColumns) end

---ONNX英文移动模型识别指定单行ROI，只输出A-Z/a-z/0-9；无检测或中文识别。
---@param frame integer 缓存帧。
---@param left integer 左边界。
---@param top integer 上边界。
---@param right integer 右边界，不含。
---@param bottom integer 下边界，不含。
---@param minimumConfidencePermille integer 最低逐字置信度0–1000，默认500。
---@return AlphanumericResult value text与averageScorePermille，无可信字符为空文本。
function Ocr.alphanumeric(frame, left, top, right, bottom, minimumConfidencePermille) end

